package de.jmonitoring.DataHandling.CounterChange;

import de.jmonitoring.base.MoniSoftConstants;
import de.jmonitoring.base.sensors.SensorInformation;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * This dialog shows the parameters a a (potential) chounter change and lets the
 * user decibe what to do
 *
 * @author togro
 */
public class CounterChangeErrorDialog extends javax.swing.JDialog {

    private int result;
    public static final int CANCEL = 0;
    public static final int CONTINUE = 1;
    public static final int CHANGECOUNTER = 2;
    public static final int CANCEL_AND_SAVE_DECISION = 3;

    /**
     * Creates new form CounterChangeErrorDialog
     */
    public CounterChangeErrorDialog(java.awt.Frame parent, boolean modal, int sensorID, Double v1, Double v2, Date startDate, Date endDate) {
        super(parent, modal);
        initComponents();        
        setAlwaysOnTop(true);
        DecimalFormat df = new DecimalFormat("0.##");
        messpunktLabel.setText(SensorInformation.getDisplayName(sensorID) + " " + SensorInformation.getSensorProperties(sensorID).getSensorDescription());
        startDateLabel.setText(new SimpleDateFormat(MoniSoftConstants.HumanDateTimeFormat).format(startDate));
        endDateLabel.setText(new SimpleDateFormat(MoniSoftConstants.HumanDateTimeFormat).format(endDate));
        counterStartLabel.setText(df.format(v1));
        counterEndLabel.setText(df.format(v2));
    }

    /**
     * Return the result of the dialog
     * @return 
     */
    public int getResult() {
        return result;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        startDateLabel = new javax.swing.JLabel();
        endDateLabel = new javax.swing.JLabel();
        counterStartLabel = new javax.swing.JLabel();
        counterEndLabel = new javax.swing.JLabel();
        addCounterChangeButton = new javax.swing.JButton();
        showEditorButton = new javax.swing.JButton();
        unit1Label = new javax.swing.JLabel();
        unit2Label = new javax.swing.JLabel();
        messpunktLabel = new javax.swing.JLabel();
        makeIntervallNullButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(440, 100));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setEnabled(false);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/jmonitoring/Components/Bundle"); // NOI18N
        jTextArea1.setText(bundle.getString("CounterChangeErrorDialog.jTextArea1.text")); // NOI18N
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/info.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setRequestFocusEnabled(false);
        jButton1.setRolloverEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(43, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel1.setText(bundle.getString("CounterChangeErrorDialog.jLabel1.text")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel2.setText(bundle.getString("CounterChangeErrorDialog.jLabel2.text")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel3.setText(bundle.getString("CounterChangeErrorDialog.jLabel3.text")); // NOI18N

        startDateLabel.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        startDateLabel.setText(bundle.getString("CounterChangeErrorDialog.startDateLabel.text")); // NOI18N

        endDateLabel.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        endDateLabel.setText(bundle.getString("CounterChangeErrorDialog.endDateLabel.text")); // NOI18N

        counterStartLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        counterStartLabel.setText(bundle.getString("CounterChangeErrorDialog.counterStartLabel.text")); // NOI18N

        counterEndLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        counterEndLabel.setText(bundle.getString("CounterChangeErrorDialog.counterEndLabel.text")); // NOI18N

        addCounterChangeButton.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        addCounterChangeButton.setText(bundle.getString("CounterChangeErrorDialog.addCounterChangeButton.text")); // NOI18N
        addCounterChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCounterChangeButtonActionPerformed(evt);
            }
        });

        showEditorButton.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        showEditorButton.setText(bundle.getString("CounterChangeErrorDialog.showEditorButton.text")); // NOI18N
        showEditorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showEditorButtonActionPerformed(evt);
            }
        });

        unit1Label.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        unit1Label.setText(bundle.getString("CounterChangeErrorDialog.unit1Label.text")); // NOI18N

        unit2Label.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        unit2Label.setText(bundle.getString("CounterChangeErrorDialog.unit2Label.text")); // NOI18N

        messpunktLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        messpunktLabel.setText(bundle.getString("CounterChangeErrorDialog.messpunktLabel.text")); // NOI18N

        makeIntervallNullButton.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        makeIntervallNullButton.setText(bundle.getString("CounterChangeErrorDialog.makeIntervallNullButton.text")); // NOI18N
        makeIntervallNullButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeIntervallNullButtonActionPerformed(evt);
            }
        });

        java.util.ResourceBundle bundle1 = java.util.ResourceBundle.getBundle("de/jmonitoring/DataHandling/CounterChange/Bundle"); // NOI18N
        jButton2.setText(bundle1.getString("CounterChangeErrorDialog.jButton2.text")); // NOI18N
        jButton2.setMaximumSize(new java.awt.Dimension(385, 23));
        jButton2.setMinimumSize(new java.awt.Dimension(385, 23));
        jButton2.setPreferredSize(new java.awt.Dimension(385, 23));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showEditorButtonSaveForAllStepsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(showEditorButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(startDateLabel))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(endDateLabel)))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(counterStartLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(counterEndLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unit1Label)
                            .addComponent(unit2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(messpunktLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE))
                    .addComponent(makeIntervallNullButton, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addComponent(addCounterChangeButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(messpunktLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(startDateLabel)
                    .addComponent(unit1Label)
                    .addComponent(counterStartLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(endDateLabel)
                    .addComponent(unit2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(counterEndLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(showEditorButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addCounterChangeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(makeIntervallNullButton)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(81, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(101, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showEditorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showEditorButtonActionPerformed
        result = CANCEL;
        dispose();
}//GEN-LAST:event_showEditorButtonActionPerformed

    private void makeIntervallNullButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeIntervallNullButtonActionPerformed
        result = CONTINUE;
        dispose();
    }//GEN-LAST:event_makeIntervallNullButtonActionPerformed

    private void addCounterChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCounterChangeButtonActionPerformed
        result = CHANGECOUNTER;
        dispose();
    }//GEN-LAST:event_addCounterChangeButtonActionPerformed

    private void showEditorButtonSaveForAllStepsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showEditorButtonSaveForAllStepsActionPerformed
        // TODO add your handling code here:
        result = CANCEL_AND_SAVE_DECISION;
        dispose();
    }//GEN-LAST:event_showEditorButtonSaveForAllStepsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCounterChangeButton;
    private javax.swing.JLabel counterEndLabel;
    private javax.swing.JLabel counterStartLabel;
    private javax.swing.JLabel endDateLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton makeIntervallNullButton;
    private javax.swing.JLabel messpunktLabel;
    private javax.swing.JButton showEditorButton;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JLabel unit1Label;
    private javax.swing.JLabel unit2Label;
    // End of variables declaration//GEN-END:variables
}
