package de.jmonitoring.DataHandling.CounterChange;

import de.jmonitoring.base.MoniSoftConstants;
import java.awt.Color;
import java.awt.Component;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;

/**
 * This panel represents a single counter chnage entry to be placed in a
 * {@link CounterChangeItemHolder}
 *
 * @author togro
 */
public class CounterChangeItem extends javax.swing.JPanel {

    private CounterChangeDialog caller;
    private CounterChange change;

    /**
     * Creates new form CounterChangeItem
     */
    public CounterChangeItem(CounterChange change, CounterChangeDialog caller) {
        this.caller = caller;
        this.change = change;
        initComponents();
        timeLabel.setText(new SimpleDateFormat(MoniSoftConstants.HumanDateTimeFormat).format(this.change.getTime()));

        DecimalFormat df = new DecimalFormat("#0.###");
        preLabel.setText(df.format(this.change.getOldValue()));
        postLabel.setText(df.format(this.change.getNewValue()));
        try {
            factorLabel.setText(df.format(this.change.getFactor()));
        } catch (IllegalArgumentException e) {
            System.out.println("F " + this.change.getFactor());
        }
    }

    /**
     * Return the corresponding counter change
     * @return The counter change
     */
    public CounterChange getChange() {
        return this.change;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timeLabel = new javax.swing.JLabel();
        preLabel = new javax.swing.JLabel();
        postLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        factorLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(185, 204, 204));
        setPreferredSize(new java.awt.Dimension(300, 16));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        timeLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/jmonitoring/Components/Bundle"); // NOI18N
        timeLabel.setText(bundle.getString("CounterChangeItem.timeLabel.text")); // NOI18N

        preLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        preLabel.setText(bundle.getString("CounterChangeItem.preLabel.text")); // NOI18N

        postLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        postLabel.setText(bundle.getString("CounterChangeItem.postLabel.text")); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/cross.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setPreferredSize(new java.awt.Dimension(20, 20));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        factorLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        factorLabel.setText(bundle.getString("CounterChangeItem.factorLabel.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(preLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(postLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(factorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(timeLabel)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addComponent(factorLabel)
                .addComponent(postLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addComponent(preLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Löschen des Zählerwechsels aus der Liste
        Component c = getParent();
        while (!(c instanceof CounterChangeItemHolder)) {
            c = c.getParent();
        }
        caller.registerDeletedChange(change);
        ((CounterChangeItemHolder) c).removeCounterChange(this);
}//GEN-LAST:event_jButton1ActionPerformed

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        setBackground(Color.YELLOW);
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        setBackground(new Color(185, 204, 204));
    }//GEN-LAST:event_formMouseExited
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel factorLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel postLabel;
    private javax.swing.JLabel preLabel;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables
}
