/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.jmonitoring.standardPlots.comparePlot;

import java.awt.CardLayout;
import java.awt.dnd.DropTarget;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.swing.JOptionPane;

import com.toedter.calendar.JDateChooser;

import de.jmonitoring.standardPlots.common.ChartDescriber;
import de.jmonitoring.base.MainApplication;
import de.jmonitoring.base.MoniSoftConstants;
import de.jmonitoring.base.sensors.SensorProperties;
import de.jmonitoring.standardPlots.plotTabs.PlotBaseTab;
import de.jmonitoring.utils.DnDListener.SensorSelectorDropListener;
import de.jmonitoring.utils.ComboBoxModels.Models;
import de.jmonitoring.utils.intervals.DateInterval;
import de.jmonitoring.utils.intervals.MonthInterval;
import de.jmonitoring.utils.intervals.WeekInterval;
import de.jmonitoring.utils.intervals.YearInterval;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author dsl
 */
public class ComparePlotTab extends PlotBaseTab {

    private static final int COMPARE_DAYS = 0;
    private static final int COMPARE_WEEKS = 1;
    private static final int COMPARE_MONTHS = 2;
    private static final int COMPARE_YEARS = 3;
    private final MainApplication gui;
    private CompareSeriesLooks compareSensorLooks = new CompareSeriesLooks(0); //TODO: Im Moment nur ein Element, keine Collection

    /**
     * Creates new form ComparePlot
     */
    public ComparePlotTab(MainApplication gui) {
        super(gui);
        this.gui = gui;
        initComponents();
        setReapeatIntervalCooser();
        categoryChooser.addItem("24 " + java.util.ResourceBundle.getBundle("de/jmonitoring/base/Bundle").getString("HOURS"));// NOI18N
        categoryChooser.setSelectedIndex(0);
    }

    @Override
    protected String getTabName() {
        return "CompareTab"; // NOI18N
    }

    
//    Einzelne Tage vergleichen
//Kalenderwochen vergleichen
//Kalendermonate vergleichen
//Kalenderjahre vergleichen
    private void setReapeatIntervalCooser() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.addElement(java.util.ResourceBundle.getBundle("de/jmonitoring/base/Bundle").getString("COMP_DAYS"));
        model.addElement(java.util.ResourceBundle.getBundle("de/jmonitoring/base/Bundle").getString("COMP_WEEKS"));
        model.addElement(java.util.ResourceBundle.getBundle("de/jmonitoring/base/Bundle").getString("COMP_MONTHS"));
        model.addElement(java.util.ResourceBundle.getBundle("de/jmonitoring/base/Bundle").getString("COMP_YEARS"));
        repeatIntervalChooser.setModel(model);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CompareTab = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        repeatIntervalChooser = new javax.swing.JComboBox();
        cardHolder = new javax.swing.JPanel();
        day_card = new javax.swing.JPanel();
        compDay1 = new com.toedter.calendar.JDateChooser();
        compDay2 = new com.toedter.calendar.JDateChooser();
        jLabel32 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        compDay3 = new com.toedter.calendar.JDateChooser();
        jLabel47 = new javax.swing.JLabel();
        compDay4 = new com.toedter.calendar.JDateChooser();
        jLabel68 = new javax.swing.JLabel();
        compDay5 = new com.toedter.calendar.JDateChooser();
        jLabel69 = new javax.swing.JLabel();
        compDay6 = new com.toedter.calendar.JDateChooser();
        jLabel71 = new javax.swing.JLabel();
        compDay7 = new com.toedter.calendar.JDateChooser();
        jToggleButton16 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jToggleButton18 = new javax.swing.JToggleButton();
        jToggleButton19 = new javax.swing.JToggleButton();
        jToggleButton20 = new javax.swing.JToggleButton();
        jToggleButton21 = new javax.swing.JToggleButton();
        jToggleButton22 = new javax.swing.JToggleButton();
        month_card = new javax.swing.JPanel();
        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jMonthChooser2 = new com.toedter.calendar.JMonthChooser();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jYearChooser3 = new com.toedter.calendar.JYearChooser();
        jYearChooser4 = new com.toedter.calendar.JYearChooser();
        jLabel72 = new javax.swing.JLabel();
        jMonthChooser3 = new com.toedter.calendar.JMonthChooser();
        jYearChooser7 = new com.toedter.calendar.JYearChooser();
        jLabel73 = new javax.swing.JLabel();
        jMonthChooser4 = new com.toedter.calendar.JMonthChooser();
        jYearChooser8 = new com.toedter.calendar.JYearChooser();
        jLabel76 = new javax.swing.JLabel();
        jMonthChooser5 = new com.toedter.calendar.JMonthChooser();
        jYearChooser9 = new com.toedter.calendar.JYearChooser();
        jLabel77 = new javax.swing.JLabel();
        jMonthChooser6 = new com.toedter.calendar.JMonthChooser();
        jYearChooser10 = new com.toedter.calendar.JYearChooser();
        jLabel78 = new javax.swing.JLabel();
        jMonthChooser7 = new com.toedter.calendar.JMonthChooser();
        jYearChooser11 = new com.toedter.calendar.JYearChooser();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        year_card = new javax.swing.JPanel();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        jYearChooser2 = new com.toedter.calendar.JYearChooser();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        week_card = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jSpinField1 = new com.toedter.components.JSpinField();
        jSpinField2 = new com.toedter.components.JSpinField();
        jYearChooser5 = new com.toedter.calendar.JYearChooser();
        jYearChooser6 = new com.toedter.calendar.JYearChooser();
        jLabel79 = new javax.swing.JLabel();
        jSpinField3 = new com.toedter.components.JSpinField();
        jYearChooser12 = new com.toedter.calendar.JYearChooser();
        jLabel80 = new javax.swing.JLabel();
        jSpinField4 = new com.toedter.components.JSpinField();
        jYearChooser13 = new com.toedter.calendar.JYearChooser();
        jLabel81 = new javax.swing.JLabel();
        jSpinField5 = new com.toedter.components.JSpinField();
        jYearChooser14 = new com.toedter.calendar.JYearChooser();
        jLabel82 = new javax.swing.JLabel();
        jSpinField6 = new com.toedter.components.JSpinField();
        jYearChooser15 = new com.toedter.calendar.JYearChooser();
        jLabel83 = new javax.swing.JLabel();
        jSpinField7 = new com.toedter.components.JSpinField();
        jYearChooser16 = new com.toedter.calendar.JYearChooser();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        categoryChooser = new javax.swing.JComboBox();
        jLabel42 = new javax.swing.JLabel();
        ComparedrawChartButton = new javax.swing.JButton();
        compareSensorSelector = new javax.swing.JComboBox();
        jLabel43 = new javax.swing.JLabel();
        powerCheck = new javax.swing.JCheckBox();

        setLayout(new java.awt.BorderLayout());

        jLabel31.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/jmonitoring/base/Bundle"); // NOI18N
        jLabel31.setText(bundle.getString("MoniSoft.jLabel31.text")); // NOI18N

        repeatIntervalChooser.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        repeatIntervalChooser.setMinimumSize(new java.awt.Dimension(56, 20));
        repeatIntervalChooser.setPreferredSize(new java.awt.Dimension(56, 20));
        repeatIntervalChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repeatIntervalChooserActionPerformed(evt);
            }
        });

        cardHolder.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), bundle.getString("MoniSoft.cardHolder.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 9))); // NOI18N
        cardHolder.setLayout(new java.awt.CardLayout());

        compDay1.setDoubleBuffered(false);
        compDay1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        compDay2.setDoubleBuffered(false);
        compDay2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        jLabel32.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel32.setText(bundle.getString("MoniSoft.jLabel32.text")); // NOI18N

        jLabel37.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel37.setText(bundle.getString("MoniSoft.jLabel37.text")); // NOI18N

        jLabel46.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel46.setText(bundle.getString("MoniSoft.jLabel46.text")); // NOI18N

        compDay3.setDoubleBuffered(false);
        compDay3.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        jLabel47.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel47.setText(bundle.getString("MoniSoft.jLabel47.text")); // NOI18N

        compDay4.setDoubleBuffered(false);
        compDay4.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        jLabel68.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel68.setText(bundle.getString("MoniSoft.jLabel68.text")); // NOI18N

        compDay5.setDoubleBuffered(false);
        compDay5.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        jLabel69.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel69.setText(bundle.getString("MoniSoft.jLabel69.text")); // NOI18N

        compDay6.setDoubleBuffered(false);
        compDay6.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        jLabel71.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel71.setText(bundle.getString("MoniSoft.jLabel71.text")); // NOI18N

        compDay7.setDoubleBuffered(false);
        compDay7.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        jToggleButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/delete.png"))); // NOI18N
        jToggleButton16.setSelected(true);
        jToggleButton16.setFocusable(false);
        jToggleButton16.setMaximumSize(new java.awt.Dimension(105, 19));
        jToggleButton16.setMinimumSize(new java.awt.Dimension(105, 19));
        jToggleButton16.setPreferredSize(new java.awt.Dimension(105, 19));
        jToggleButton16.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/accept.png"))); // NOI18N

        jToggleButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/delete.png"))); // NOI18N
        jToggleButton17.setSelected(true);
        jToggleButton17.setFocusable(false);
        jToggleButton17.setMaximumSize(new java.awt.Dimension(105, 19));
        jToggleButton17.setMinimumSize(new java.awt.Dimension(105, 19));
        jToggleButton17.setPreferredSize(new java.awt.Dimension(105, 19));
        jToggleButton17.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/accept.png"))); // NOI18N

        jToggleButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/delete.png"))); // NOI18N
        jToggleButton18.setFocusable(false);
        jToggleButton18.setMaximumSize(new java.awt.Dimension(105, 19));
        jToggleButton18.setMinimumSize(new java.awt.Dimension(105, 19));
        jToggleButton18.setPreferredSize(new java.awt.Dimension(105, 19));
        jToggleButton18.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/accept.png"))); // NOI18N

        jToggleButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/delete.png"))); // NOI18N
        jToggleButton19.setFocusable(false);
        jToggleButton19.setMaximumSize(new java.awt.Dimension(105, 19));
        jToggleButton19.setMinimumSize(new java.awt.Dimension(105, 19));
        jToggleButton19.setPreferredSize(new java.awt.Dimension(105, 19));
        jToggleButton19.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/accept.png"))); // NOI18N

        jToggleButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/delete.png"))); // NOI18N
        jToggleButton20.setFocusable(false);
        jToggleButton20.setMaximumSize(new java.awt.Dimension(105, 19));
        jToggleButton20.setMinimumSize(new java.awt.Dimension(105, 19));
        jToggleButton20.setPreferredSize(new java.awt.Dimension(105, 19));
        jToggleButton20.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/accept.png"))); // NOI18N

        jToggleButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/delete.png"))); // NOI18N
        jToggleButton21.setFocusable(false);
        jToggleButton21.setMaximumSize(new java.awt.Dimension(105, 19));
        jToggleButton21.setMinimumSize(new java.awt.Dimension(105, 19));
        jToggleButton21.setPreferredSize(new java.awt.Dimension(105, 19));
        jToggleButton21.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/accept.png"))); // NOI18N

        jToggleButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/delete.png"))); // NOI18N
        jToggleButton22.setFocusable(false);
        jToggleButton22.setMaximumSize(new java.awt.Dimension(105, 19));
        jToggleButton22.setMinimumSize(new java.awt.Dimension(105, 19));
        jToggleButton22.setPreferredSize(new java.awt.Dimension(105, 19));
        jToggleButton22.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/accept.png"))); // NOI18N

        compDay1.getJCalendar().setTodayButtonVisible(true);
        compDay2.getJCalendar().setTodayButtonVisible(true);
        compDay3.getJCalendar().setTodayButtonVisible(true);
        compDay4.getJCalendar().setTodayButtonVisible(true);
        compDay5.getJCalendar().setTodayButtonVisible(true);
        compDay7.getJCalendar().setTodayButtonVisible(true);

        javax.swing.GroupLayout day_cardLayout = new javax.swing.GroupLayout(day_card);
        day_card.setLayout(day_cardLayout);
        day_cardLayout.setHorizontalGroup(
            day_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(day_cardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(day_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(day_cardLayout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addGap(18, 18, 18)
                        .addGroup(day_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(day_cardLayout.createSequentialGroup()
                                .addComponent(compDay2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(day_cardLayout.createSequentialGroup()
                                .addComponent(compDay1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(day_cardLayout.createSequentialGroup()
                        .addGroup(day_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel71, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                            .addComponent(jLabel69, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel68, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel47, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel46, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(day_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(day_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(day_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(compDay3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(compDay4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(compDay5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(compDay6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(compDay7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(day_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(323, Short.MAX_VALUE))
        );
        day_cardLayout.setVerticalGroup(
            day_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(day_cardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(day_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(compDay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(jToggleButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(day_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(compDay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(day_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(compDay3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46)
                    .addComponent(jToggleButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(day_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(compDay4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47)
                    .addComponent(jToggleButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(day_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(compDay5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel68)
                    .addComponent(jToggleButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(day_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(compDay6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel69)
                    .addComponent(jToggleButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(day_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compDay7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel71))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        compDay6.getJCalendar().setTodayButtonVisible(true);

        cardHolder.add(day_card, "daySelector_card");

        jLabel38.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel38.setText(bundle.getString("MoniSoft.jLabel38.text")); // NOI18N

        jLabel39.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel39.setText(bundle.getString("MoniSoft.jLabel39.text")); // NOI18N

        jLabel72.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel72.setText(bundle.getString("MoniSoft.jLabel72.text")); // NOI18N

        jLabel73.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel73.setText(bundle.getString("MoniSoft.jLabel73.text")); // NOI18N

        jLabel76.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel76.setText(bundle.getString("MoniSoft.jLabel76.text")); // NOI18N

        jLabel77.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel77.setText(bundle.getString("MoniSoft.jLabel77.text")); // NOI18N

        jLabel78.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel78.setText(bundle.getString("MoniSoft.jLabel78.text")); // NOI18N

        jToggleButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/delete.png"))); // NOI18N
        jToggleButton9.setSelected(true);
        jToggleButton9.setMaximumSize(new java.awt.Dimension(105, 19));
        jToggleButton9.setMinimumSize(new java.awt.Dimension(105, 19));
        jToggleButton9.setPreferredSize(new java.awt.Dimension(105, 19));
        jToggleButton9.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/accept.png"))); // NOI18N

        jToggleButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/delete.png"))); // NOI18N
        jToggleButton10.setSelected(true);
        jToggleButton10.setMaximumSize(new java.awt.Dimension(105, 19));
        jToggleButton10.setMinimumSize(new java.awt.Dimension(105, 19));
        jToggleButton10.setPreferredSize(new java.awt.Dimension(105, 19));
        jToggleButton10.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/accept.png"))); // NOI18N

        jToggleButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/delete.png"))); // NOI18N
        jToggleButton11.setMaximumSize(new java.awt.Dimension(105, 19));
        jToggleButton11.setMinimumSize(new java.awt.Dimension(105, 19));
        jToggleButton11.setPreferredSize(new java.awt.Dimension(105, 19));
        jToggleButton11.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/accept.png"))); // NOI18N

        jToggleButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/delete.png"))); // NOI18N
        jToggleButton12.setMaximumSize(new java.awt.Dimension(105, 19));
        jToggleButton12.setMinimumSize(new java.awt.Dimension(105, 19));
        jToggleButton12.setPreferredSize(new java.awt.Dimension(105, 19));
        jToggleButton12.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/accept.png"))); // NOI18N

        jToggleButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/delete.png"))); // NOI18N
        jToggleButton13.setMaximumSize(new java.awt.Dimension(105, 19));
        jToggleButton13.setMinimumSize(new java.awt.Dimension(105, 19));
        jToggleButton13.setPreferredSize(new java.awt.Dimension(105, 19));
        jToggleButton13.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/accept.png"))); // NOI18N

        jToggleButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/delete.png"))); // NOI18N
        jToggleButton14.setMaximumSize(new java.awt.Dimension(105, 19));
        jToggleButton14.setMinimumSize(new java.awt.Dimension(105, 19));
        jToggleButton14.setPreferredSize(new java.awt.Dimension(105, 19));
        jToggleButton14.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/accept.png"))); // NOI18N

        jToggleButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/delete.png"))); // NOI18N
        jToggleButton15.setMaximumSize(new java.awt.Dimension(105, 19));
        jToggleButton15.setMinimumSize(new java.awt.Dimension(105, 19));
        jToggleButton15.setPreferredSize(new java.awt.Dimension(105, 19));
        jToggleButton15.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/accept.png"))); // NOI18N

        javax.swing.GroupLayout month_cardLayout = new javax.swing.GroupLayout(month_card);
        month_card.setLayout(month_cardLayout);
        month_cardLayout.setHorizontalGroup(
            month_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(month_cardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(month_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(month_cardLayout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addComponent(jMonthChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jYearChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(month_cardLayout.createSequentialGroup()
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jMonthChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jYearChooser4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, month_cardLayout.createSequentialGroup()
                        .addComponent(jLabel72, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jMonthChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jYearChooser7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(month_cardLayout.createSequentialGroup()
                        .addComponent(jLabel73, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jMonthChooser4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jYearChooser8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(month_cardLayout.createSequentialGroup()
                        .addComponent(jLabel76, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jMonthChooser5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jYearChooser9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(month_cardLayout.createSequentialGroup()
                        .addComponent(jLabel77, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jMonthChooser6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jYearChooser10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(month_cardLayout.createSequentialGroup()
                        .addComponent(jLabel78, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jMonthChooser7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jYearChooser11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(month_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(172, 172, 172))
        );
        month_cardLayout.setVerticalGroup(
            month_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(month_cardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(month_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToggleButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(month_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel38)
                        .addComponent(jYearChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jMonthChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(month_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39)
                    .addComponent(jYearChooser4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMonthChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(month_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jYearChooser7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMonthChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel72)
                    .addComponent(jToggleButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(month_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(month_cardLayout.createSequentialGroup()
                        .addGroup(month_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jYearChooser8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMonthChooser4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel73))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(month_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jYearChooser9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMonthChooser5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel76)))
                    .addGroup(month_cardLayout.createSequentialGroup()
                        .addComponent(jToggleButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(month_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(month_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jYearChooser10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jMonthChooser6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel77))
                    .addComponent(jToggleButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(month_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jMonthChooser7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel78)
                    .addGroup(month_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jToggleButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jYearChooser11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardHolder.add(month_card, "monthSelector_card");

        jLabel40.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel40.setText(bundle.getString("MoniSoft.jLabel40.text")); // NOI18N

        jLabel41.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel41.setText(bundle.getString("MoniSoft.jLabel41.text")); // NOI18N

        javax.swing.GroupLayout year_cardLayout = new javax.swing.GroupLayout(year_card);
        year_card.setLayout(year_cardLayout);
        year_cardLayout.setHorizontalGroup(
            year_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(year_cardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(year_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(year_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jYearChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jYearChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addContainerGap(429, Short.MAX_VALUE))
        );
        year_cardLayout.setVerticalGroup(
            year_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(year_cardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(year_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addComponent(jYearChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(year_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41)
                    .addComponent(jYearChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        cardHolder.add(year_card, "yearSelector_card");

        jLabel44.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel44.setText(bundle.getString("MoniSoft.jLabel44.text")); // NOI18N

        jLabel45.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel45.setText(bundle.getString("MoniSoft.jLabel45.text")); // NOI18N

        jSpinField1.setMaximum(52);
        jSpinField1.setMinimum(1);
        jSpinField1.setValue(1);

        jSpinField2.setMaximum(52);
        jSpinField2.setMinimum(1);
        jSpinField2.setValue(1);

        jLabel79.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel79.setText(bundle.getString("MoniSoft.jLabel79.text")); // NOI18N

        jSpinField3.setMaximum(52);
        jSpinField3.setMinimum(1);
        jSpinField3.setValue(1);

        jLabel80.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel80.setText(bundle.getString("MoniSoft.jLabel80.text")); // NOI18N

        jSpinField4.setMaximum(52);
        jSpinField4.setMinimum(1);
        jSpinField4.setValue(1);

        jLabel81.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel81.setText(bundle.getString("MoniSoft.jLabel81.text")); // NOI18N

        jSpinField5.setMaximum(52);
        jSpinField5.setMinimum(1);
        jSpinField5.setValue(1);

        jLabel82.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel82.setText(bundle.getString("MoniSoft.jLabel82.text")); // NOI18N

        jSpinField6.setMaximum(52);
        jSpinField6.setMinimum(1);
        jSpinField6.setValue(1);

        jLabel83.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel83.setText(bundle.getString("MoniSoft.jLabel83.text")); // NOI18N

        jSpinField7.setMaximum(52);
        jSpinField7.setMinimum(1);
        jSpinField7.setValue(1);

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/delete.png"))); // NOI18N
        jToggleButton2.setSelected(true);
        jToggleButton2.setMaximumSize(new java.awt.Dimension(105, 19));
        jToggleButton2.setMinimumSize(new java.awt.Dimension(105, 19));
        jToggleButton2.setPreferredSize(new java.awt.Dimension(105, 19));
        jToggleButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/accept.png"))); // NOI18N

        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/delete.png"))); // NOI18N
        jToggleButton3.setMaximumSize(new java.awt.Dimension(105, 19));
        jToggleButton3.setMinimumSize(new java.awt.Dimension(105, 19));
        jToggleButton3.setPreferredSize(new java.awt.Dimension(105, 19));
        jToggleButton3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/accept.png"))); // NOI18N

        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/delete.png"))); // NOI18N
        jToggleButton4.setMaximumSize(new java.awt.Dimension(105, 19));
        jToggleButton4.setMinimumSize(new java.awt.Dimension(105, 19));
        jToggleButton4.setPreferredSize(new java.awt.Dimension(105, 19));
        jToggleButton4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/accept.png"))); // NOI18N

        jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/delete.png"))); // NOI18N
        jToggleButton5.setMaximumSize(new java.awt.Dimension(105, 19));
        jToggleButton5.setMinimumSize(new java.awt.Dimension(105, 19));
        jToggleButton5.setPreferredSize(new java.awt.Dimension(105, 19));
        jToggleButton5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/accept.png"))); // NOI18N

        jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/delete.png"))); // NOI18N
        jToggleButton6.setMaximumSize(new java.awt.Dimension(105, 19));
        jToggleButton6.setMinimumSize(new java.awt.Dimension(105, 19));
        jToggleButton6.setPreferredSize(new java.awt.Dimension(105, 19));
        jToggleButton6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/accept.png"))); // NOI18N

        jToggleButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/delete.png"))); // NOI18N
        jToggleButton7.setMaximumSize(new java.awt.Dimension(105, 19));
        jToggleButton7.setMinimumSize(new java.awt.Dimension(105, 19));
        jToggleButton7.setPreferredSize(new java.awt.Dimension(105, 19));
        jToggleButton7.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/accept.png"))); // NOI18N

        jToggleButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/delete.png"))); // NOI18N
        jToggleButton8.setSelected(true);
        jToggleButton8.setMaximumSize(new java.awt.Dimension(105, 19));
        jToggleButton8.setMinimumSize(new java.awt.Dimension(105, 19));
        jToggleButton8.setPreferredSize(new java.awt.Dimension(105, 19));
        jToggleButton8.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/accept.png"))); // NOI18N

        javax.swing.GroupLayout week_cardLayout = new javax.swing.GroupLayout(week_card);
        week_card.setLayout(week_cardLayout);
        week_cardLayout.setHorizontalGroup(
            week_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(week_cardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(week_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(week_cardLayout.createSequentialGroup()
                        .addComponent(jLabel83, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                        .addGap(25, 25, 25)
                        .addComponent(jSpinField7, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jYearChooser16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(week_cardLayout.createSequentialGroup()
                        .addComponent(jLabel82, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                        .addGap(25, 25, 25)
                        .addComponent(jSpinField6, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jYearChooser15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(week_cardLayout.createSequentialGroup()
                        .addComponent(jLabel81, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                        .addGap(25, 25, 25)
                        .addComponent(jSpinField5, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jYearChooser14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(week_cardLayout.createSequentialGroup()
                        .addComponent(jLabel80, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                        .addGap(25, 25, 25)
                        .addComponent(jSpinField4, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jYearChooser13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, week_cardLayout.createSequentialGroup()
                        .addGroup(week_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(week_cardLayout.createSequentialGroup()
                                .addGroup(week_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(week_cardLayout.createSequentialGroup()
                                .addComponent(jLabel79, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(25, 25, 25)))
                        .addGroup(week_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(week_cardLayout.createSequentialGroup()
                                .addGroup(week_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSpinField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSpinField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(week_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(week_cardLayout.createSequentialGroup()
                                        .addComponent(jYearChooser5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(week_cardLayout.createSequentialGroup()
                                        .addComponent(jYearChooser6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToggleButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(week_cardLayout.createSequentialGroup()
                                .addComponent(jSpinField3, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jYearChooser12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(254, 254, 254))
        );
        week_cardLayout.setVerticalGroup(
            week_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(week_cardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(week_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel44)
                    .addComponent(jSpinField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jYearChooser5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(week_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel45)
                    .addComponent(jSpinField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jYearChooser6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(week_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel79)
                    .addComponent(jSpinField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jYearChooser12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(week_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel80)
                    .addComponent(jSpinField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jYearChooser13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(week_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(week_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jYearChooser14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel81)
                        .addComponent(jSpinField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(week_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(week_cardLayout.createSequentialGroup()
                        .addGroup(week_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jYearChooser15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel82)
                            .addComponent(jSpinField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(week_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jYearChooser16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel83)
                            .addComponent(jSpinField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(week_cardLayout.createSequentialGroup()
                        .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        cardHolder.add(week_card, "weekSelector_card");

        categoryChooser.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        categoryChooser.setMinimumSize(new java.awt.Dimension(56, 20));
        categoryChooser.setPreferredSize(new java.awt.Dimension(56, 20));

        jLabel42.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel42.setText(bundle.getString("MoniSoft.jLabel42.text")); // NOI18N

        ComparedrawChartButton.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        ComparedrawChartButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/chart--pencil.png"))); // NOI18N
        ComparedrawChartButton.setText(bundle.getString("MoniSoft.ComparedrawChartButton.text")); // NOI18N
        ComparedrawChartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComparedrawChartButtonActionPerformed(evt);
            }
        });

        compareSensorSelector.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        compareSensorSelector.setMaximumRowCount(20);
        compareSensorSelector.setMinimumSize(new java.awt.Dimension(126, 17));
        compareSensorSelector.setPreferredSize(new java.awt.Dimension(126, 17));
        compareSensorSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compareSensorSelectorActionPerformed(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jLabel43.setText(bundle.getString("MoniSoft.jLabel43.text")); // NOI18N

        powerCheck.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        powerCheck.setText(bundle.getString("MoniSoft.powerCheck.text")); // NOI18N
        powerCheck.setEnabled(false);

        DropTarget dt_CompareSensorSelector = new DropTarget(compareSensorSelector,new SensorSelectorDropListener());

        javax.swing.GroupLayout CompareTabLayout = new javax.swing.GroupLayout(CompareTab);
        CompareTab.setLayout(CompareTabLayout);
        CompareTabLayout.setHorizontalGroup(
            CompareTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CompareTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CompareTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cardHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(CompareTabLayout.createSequentialGroup()
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(repeatIntervalChooser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(CompareTabLayout.createSequentialGroup()
                        .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(categoryChooser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CompareTabLayout.createSequentialGroup()
                        .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(compareSensorSelector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CompareTabLayout.createSequentialGroup()
                        .addComponent(powerCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ComparedrawChartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        CompareTabLayout.setVerticalGroup(
            CompareTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CompareTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CompareTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(repeatIntervalChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CompareTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(categoryChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(cardHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CompareTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(compareSensorSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CompareTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(powerCheck)
                    .addComponent(ComparedrawChartButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(CompareTab, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // TODO: replace switch with class
    private void repeatIntervalChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repeatIntervalChooserActionPerformed
        CardLayout cardLayout = (CardLayout) cardHolder.getLayout();
        switch (repeatIntervalChooser.getSelectedIndex()) {
            case COMPARE_DAYS:
                cardLayout.show(cardHolder, "daySelector_card");// NOI18N
                categoryChooser.removeAllItems();
                categoryChooser.addItem("24 " + java.util.ResourceBundle.getBundle("de/jmonitoring/base/Bundle").getString("HOURS"));// NOI18N
                break;
            case COMPARE_WEEKS:
                cardLayout.show(cardHolder, "weekSelector_card");// NOI18N
                categoryChooser.removeAllItems();
                categoryChooser.addItem("168 " + java.util.ResourceBundle.getBundle("de/jmonitoring/base/Bundle").getString("HOURS") + " (7 " + java.util.ResourceBundle.getBundle("de/jmonitoring/base/Bundle").getString("DAYS") + " " + java.util.ResourceBundle.getBundle("de/jmonitoring/base/Bundle").getString("JE") + " 24 " + java.util.ResourceBundle.getBundle("de/jmonitoring/base/Bundle").getString("HOURS"));// NOI18N
                categoryChooser.addItem("7 " + java.util.ResourceBundle.getBundle("de/jmonitoring/base/Bundle").getString("DAYS"));// NOI18N
                break;
            case COMPARE_MONTHS:
                cardLayout.show(cardHolder, "monthSelector_card");// NOI18N
                categoryChooser.removeAllItems();
                categoryChooser.addItem("720 " + java.util.ResourceBundle.getBundle("de/jmonitoring/base/Bundle").getString("HOURS") + " (30 " + java.util.ResourceBundle.getBundle("de/jmonitoring/base/Bundle").getString("DAYS") + " " + java.util.ResourceBundle.getBundle("de/jmonitoring/base/Bundle").getString("JE") + " 24 " + java.util.ResourceBundle.getBundle("de/jmonitoring/base/Bundle").getString("HOURS"));// NOI18N
                categoryChooser.addItem("30 " + java.util.ResourceBundle.getBundle("de/jmonitoring/base/Bundle").getString("DAYS"));// NOI18N
                break;
            case COMPARE_YEARS:
                cardLayout.show(cardHolder, "yearSelector_card");// NOI18N
                categoryChooser.removeAllItems();
                categoryChooser.addItem("8760 " + java.util.ResourceBundle.getBundle("de/jmonitoring/base/Bundle").getString("HOURS") + " (365 " + java.util.ResourceBundle.getBundle("de/jmonitoring/base/Bundle").getString("DAYS") + " " + java.util.ResourceBundle.getBundle("de/jmonitoring/base/Bundle").getString("JE") + " 24 " + java.util.ResourceBundle.getBundle("de/jmonitoring/base/Bundle").getString("HOURS"));// NOI18N
                categoryChooser.addItem("365 " + java.util.ResourceBundle.getBundle("de/jmonitoring/base/Bundle").getString("DAYS"));// NOI18N
                categoryChooser.addItem("12 " + java.util.ResourceBundle.getBundle("de/jmonitoring/base/Bundle").getString("MONTHS"));// NOI18N
                break;
        }
    }//GEN-LAST:event_repeatIntervalChooserActionPerformed

    private Iterable<JDateChooser> getDayChoosers() {
        return Arrays.asList(compDay1, compDay2, compDay3, compDay4, compDay5, compDay6, compDay7);
    }

    private void addDayPeriod(JDateChooser dayChooser, List periods) {
        if (dayChooser.getDate() != null) {
            periods.add(new DateInterval(dayChooser.getDate(), dayChooser.getDate()));
        }
    }

    private void ComparedrawChartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComparedrawChartButtonActionPerformed
        List periods = new ArrayList();
        switch (repeatIntervalChooser.getSelectedIndex()) {
            case COMPARE_DAYS: // Tagesperioden
                for (JDateChooser dayChooser : getDayChoosers()) {
                    addDayPeriod(dayChooser, periods);
                }
                break;
            case COMPARE_WEEKS: //Wochenperioden
                if (jToggleButton2.isSelected()) {
                    periods.add(new WeekInterval(jSpinField1.getValue(), jYearChooser5.getValue(), jSpinField1.getValue(), jYearChooser5.getValue()));
                }
                if (jToggleButton8.isSelected()) {
                    periods.add(new WeekInterval(jSpinField2.getValue(), jYearChooser6.getValue(), jSpinField2.getValue(), jYearChooser6.getValue()));
                }
                if (jToggleButton7.isSelected()) {
                    periods.add(new WeekInterval(jSpinField3.getValue(), jYearChooser12.getValue(), jSpinField3.getValue(), jYearChooser12.getValue()));
                }
                if (jToggleButton6.isSelected()) {
                    periods.add(new WeekInterval(jSpinField4.getValue(), jYearChooser13.getValue(), jSpinField4.getValue(), jYearChooser13.getValue()));
                }
                if (jToggleButton5.isSelected()) {
                    periods.add(new WeekInterval(jSpinField5.getValue(), jYearChooser14.getValue(), jSpinField5.getValue(), jYearChooser14.getValue()));
                }
                if (jToggleButton4.isSelected()) {
                    periods.add(new WeekInterval(jSpinField6.getValue(), jYearChooser15.getValue(), jSpinField6.getValue(), jYearChooser15.getValue()));
                }
                if (jToggleButton3.isSelected()) {
                    periods.add(new WeekInterval(jSpinField7.getValue(), jYearChooser16.getValue(), jSpinField7.getValue(), jYearChooser16.getValue()));
                }
                break;
            case COMPARE_MONTHS: //Monatsperioden
                if (jToggleButton9.isSelected()) {
                    periods.add(new MonthInterval(jMonthChooser1.getMonth(), jYearChooser3.getValue(), jMonthChooser1.getMonth(), jYearChooser3.getValue()));
                }
                if (jToggleButton10.isSelected()) {
                    periods.add(new MonthInterval(jMonthChooser2.getMonth(), jYearChooser4.getValue(), jMonthChooser2.getMonth(), jYearChooser4.getValue()));
                }
                if (jToggleButton11.isSelected()) {
                    periods.add(new MonthInterval(jMonthChooser3.getMonth(), jYearChooser7.getValue(), jMonthChooser3.getMonth(), jYearChooser7.getValue()));
                }
                if (jToggleButton12.isSelected()) {
                    periods.add(new MonthInterval(jMonthChooser4.getMonth(), jYearChooser8.getValue(), jMonthChooser4.getMonth(), jYearChooser8.getValue()));
                }
                if (jToggleButton13.isSelected()) {
                    periods.add(new MonthInterval(jMonthChooser5.getMonth(), jYearChooser9.getValue(), jMonthChooser5.getMonth(), jYearChooser9.getValue()));
                }
                if (jToggleButton14.isSelected()) {
                    periods.add(new MonthInterval(jMonthChooser6.getMonth(), jYearChooser10.getValue(), jMonthChooser6.getMonth(), jYearChooser10.getValue()));
                }
                if (jToggleButton15.isSelected()) {
                    periods.add(new MonthInterval(jMonthChooser7.getMonth(), jYearChooser11.getValue(), jMonthChooser7.getMonth(), jYearChooser11.getValue()));
                }
                break;
            case COMPARE_YEARS:
                periods.add(new YearInterval(jYearChooser1.getYear(), jYearChooser1.getYear()));
                periods.add(new YearInterval(jYearChooser2.getYear(), jYearChooser2.getYear()));
                break;

        }

        if (periods.isEmpty()) {
            JOptionPane.showMessageDialog(this.gui.getMainFrame(), java.util.ResourceBundle.getBundle("de/jmonitoring/base/Bundle").getString("NO_COMPARE_PERIOD"));// NOI18N
            return;
        }
        // Im Moment nur ein Sensor - daher hier manuell in die SeriesLooksCollection schrieben
        if (((SensorProperties) compareSensorSelector.getSelectedItem()).getSensorName().equals(MoniSoftConstants.NO_SENSOR_SELECTED)) {
            JOptionPane.showMessageDialog(this.gui.getMainFrame(), java.util.ResourceBundle.getBundle("de/jmonitoring/base/Bundle").getString("SIE HABEN KEINE MESSPUNKTE AUSGEWÄHLT."));// NOI18N
            return;
        }
        SensorProperties selectedSensor = (SensorProperties) compareSensorSelector.getSelectedItem();
        compareSensorLooks.setSensor(selectedSensor.getSensorName());
        compareSensorLooks.setLegendString(null);
        compareSensorLooks.setSensorID(selectedSensor.getSensorID());
        compareSensorLooks.setUnit(selectedSensor.getSensorUnit().getUnit());
        compareSensorLooks.setPowerWanted(powerCheck.isSelected());
        compareSensorLooks.setFactor(selectedSensor.getFactor());
        ArrayList compareSeriesLooksCollection = new ArrayList();
        compareSeriesLooksCollection.add(compareSensorLooks);

        // TODO Prüfen ob mehr mindestens Perioden
        gui().drawChart(new CompareChartDescriber(java.util.ResourceBundle.getBundle("de/jmonitoring/base/Bundle").getString("MoniSoft.CompareTab.TabConstraints.tabTitle"), periods, categoryChooser.getSelectedIndex(), compareSeriesLooksCollection));// NOI18N
    }//GEN-LAST:event_ComparedrawChartButtonActionPerformed

    private void compareSensorSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compareSensorSelectorActionPerformed
        SensorProperties props = (SensorProperties) compareSensorSelector.getSelectedItem();
        if (props != null && !props.getSensorName().equals(MoniSoftConstants.NO_SENSOR_SELECTED) && (props.isCounter() || props.isUsage())) {
            powerCheck.setEnabled(true);
            //            referenceSelector.setEnabled(true);
        } else {
            powerCheck.setEnabled(false);
            powerCheck.setSelected(false);
            //            referenceSelector.setEnabled(false);
        }
    }//GEN-LAST:event_compareSensorSelectorActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CompareTab;
    private javax.swing.JButton ComparedrawChartButton;
    private javax.swing.JPanel cardHolder;
    private javax.swing.JComboBox categoryChooser;
    static com.toedter.calendar.JDateChooser compDay1;
    static com.toedter.calendar.JDateChooser compDay2;
    static com.toedter.calendar.JDateChooser compDay3;
    static com.toedter.calendar.JDateChooser compDay4;
    static com.toedter.calendar.JDateChooser compDay5;
    static com.toedter.calendar.JDateChooser compDay6;
    static com.toedter.calendar.JDateChooser compDay7;
    static javax.swing.JComboBox compareSensorSelector;
    private javax.swing.JPanel day_card;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private com.toedter.calendar.JMonthChooser jMonthChooser2;
    private com.toedter.calendar.JMonthChooser jMonthChooser3;
    private com.toedter.calendar.JMonthChooser jMonthChooser4;
    private com.toedter.calendar.JMonthChooser jMonthChooser5;
    private com.toedter.calendar.JMonthChooser jMonthChooser6;
    private com.toedter.calendar.JMonthChooser jMonthChooser7;
    private com.toedter.components.JSpinField jSpinField1;
    private com.toedter.components.JSpinField jSpinField2;
    private com.toedter.components.JSpinField jSpinField3;
    private com.toedter.components.JSpinField jSpinField4;
    private com.toedter.components.JSpinField jSpinField5;
    private com.toedter.components.JSpinField jSpinField6;
    private com.toedter.components.JSpinField jSpinField7;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton21;
    private javax.swing.JToggleButton jToggleButton22;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private com.toedter.calendar.JYearChooser jYearChooser10;
    private com.toedter.calendar.JYearChooser jYearChooser11;
    private com.toedter.calendar.JYearChooser jYearChooser12;
    private com.toedter.calendar.JYearChooser jYearChooser13;
    private com.toedter.calendar.JYearChooser jYearChooser14;
    private com.toedter.calendar.JYearChooser jYearChooser15;
    private com.toedter.calendar.JYearChooser jYearChooser16;
    private com.toedter.calendar.JYearChooser jYearChooser2;
    private com.toedter.calendar.JYearChooser jYearChooser3;
    private com.toedter.calendar.JYearChooser jYearChooser4;
    private com.toedter.calendar.JYearChooser jYearChooser5;
    private com.toedter.calendar.JYearChooser jYearChooser6;
    private com.toedter.calendar.JYearChooser jYearChooser7;
    private com.toedter.calendar.JYearChooser jYearChooser8;
    private com.toedter.calendar.JYearChooser jYearChooser9;
    private javax.swing.JPanel month_card;
    private javax.swing.JCheckBox powerCheck;
    private javax.swing.JComboBox repeatIntervalChooser;
    private javax.swing.JPanel week_card;
    private javax.swing.JPanel year_card;
    // End of variables declaration//GEN-END:variables

    @Override
    public Result fillFrom(ChartDescriber chartDescriber) {
        return Result.IGNORED;
    }

    @Override
    public void setIntervalSelector(Models models) {
        // does nothing
    }

    @Override
    public void resetCollections(int index) {
        // does nothing
    }

    @Override
    public void lockDates(boolean lock) {
        // does nothing
    }

    @Override
    public void clearSelections() {
        compareSensorSelector.removeAllItems();
    }

    @Override
    public void setSelectionsFrom(Models models) {
        compareSensorSelector.setModel(models.getSensorListComboBoxModel());
    }

    @Override
    public void clearData() {
        // does nothing
    }

    @Override
    public DateInterval getSelectedInterval() {
        return null;
    }

    @Override
    public void setSelectedInterval(DateInterval newInterval) {
        // does nothing
    }

    @Override
    public void fillAnnotationChooser() {
        // do nothing
    }
}
