package de.jmonitoring.References;

import de.jmonitoring.Components.BuildingEditorDialog;
import de.jmonitoring.utils.UnitCalulation.UnitInformation;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 * This panel is used to edit or define {@link ReferenceDescription}s<p> These
 * descriptions can then be filled with values for each building representing a
 * reference value
 *
 * @author togro
 */
public class ReferenceDefinitionAddPanel extends javax.swing.JPanel {

    private final ReferenceDefinitionDialog caller;

    /**
     * Create a new panel
     *
     * @param editable Determine if this panel is view only or editable
     * @param bd The calling {@link ReferenceDefinitionDialog}
     */
    public ReferenceDefinitionAddPanel(boolean editable, ReferenceDefinitionDialog bd) {
        initComponents();
        this.caller = bd;
        unitComboBox.setEnabled(editable);
        nameTextField.setEnabled(editable);
        descriptionTextField.setEnabled(editable);
        unitComboBox.setModel(new DefaultComboBoxModel(UnitInformation.getUnitList().values().toArray()));
    }

    /**
     * Set the fields according to the given {@link ReferenceDescription}
     *
     * @param refDef The reference
     */
    public void setFields(ReferenceDescription refDef) {
        nameTextField.setText(refDef.getName());
        descriptionTextField.setText(refDef.getDescription());
        unitComboBox.setSelectedItem(UnitInformation.getUnitNameFromID(refDef.getUnitID()));
    }

    /**
     * Builds an new {@link ReferenceDescription} out of the panles fields
     *
     * @return The new {@link ReferenceDescription}
     */
    public ReferenceDescription getReferenceFields() {
        // Prüfen ob gültiger Name
        if (nameTextField.getText().trim().isEmpty()) {
            return null;
        }

        // Wenn erfüllt Referencevalue erzeugen
        return new ReferenceDescription(nameTextField.getText().trim(), descriptionTextField.getText().trim(), UnitInformation.getIDFromUnitName(unitComboBox.getSelectedItem().toString()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        unitLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        descriptionTextField = new javax.swing.JTextField();
        unitComboBox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        nameLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/jmonitoring/References/Bundle"); // NOI18N
        nameLabel.setText(bundle.getString("ReferenceDefinitionAddPanel.nameLabel.text")); // NOI18N

        valueLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        valueLabel.setText(bundle.getString("ReferenceDefinitionAddPanel.valueLabel.text")); // NOI18N

        unitLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        unitLabel.setText(bundle.getString("ReferenceDefinitionAddPanel.unitLabel.text")); // NOI18N

        unitComboBox.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        unitComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        unitComboBox.setMinimumSize(new java.awt.Dimension(71, 19));
        unitComboBox.setPreferredSize(new java.awt.Dimension(71, 19));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/add.png"))); // NOI18N
        jButton1.setToolTipText(bundle.getString("ReferenceDefinitionAddPanel.jButton1.toolTipText")); // NOI18N
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.setMaximumSize(new java.awt.Dimension(25, 25));
        jButton1.setMinimumSize(new java.awt.Dimension(25, 25));
        jButton1.setPreferredSize(new java.awt.Dimension(25, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 105, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descriptionTextField)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(unitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(unitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(nameLabel)
                    .addComponent(valueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(unitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (getReferenceFields() != null) { // wenn es eine gültige Bezugsgröße ist
            caller.getReferenceDefinitionHolder().addReference(getReferenceFields());
            caller.updateScrollPane(BuildingEditorDialog.BOTTOM);
        } else { // sonst warnen
            JOptionPane.showMessageDialog(this, "Dies ist keine gültige Bezugsgröße.", "Keine Bezugsgröße", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JComboBox unitComboBox;
    private javax.swing.JLabel unitLabel;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
