package de.jmonitoring.References;

import de.jmonitoring.base.Messages;
import de.jmonitoring.base.MoniSoft;
import de.jmonitoring.base.MoniSoftConstants;
import de.jmonitoring.help.ManualBookmarks;
import de.jmonitoring.help.ManualViewer;
import javax.swing.JScrollBar;
import javax.swing.SwingUtilities;

/**
 * This Dialog enables the listing, creation and editing of
 * {@link ReferenceDescription}s
 *
 * @author togro
 */
public class ReferenceDefinitionDialog extends javax.swing.JDialog {

    private final ReferenceDefinitionHolder refHolder;
    private final ReferenceDefinitionAddPanel refAddPanel = new ReferenceDefinitionAddPanel(true, this);
    public static final int TOP = 0;
    public static final int BOTTOM = 1;
    public static final int LEAVE = 2;

    /**
     * Creates new form ReferenceDefinitionDialog
     *
     * @param parent The calling parent
     * @param modal The modality mode
     */
    public ReferenceDefinitionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        refHolder = new ReferenceDefinitionHolder(true, this);
        set();
    }

    /**
     * Load all known {@link ReferenceDescription}s and show them in the
     * {@link ReferenceDefinitionHolder}
     */
    private void set() {
        // Referenzpanel belegen mit den Referenzen für das Gebäude
        for (ReferenceDescription ref : ReferenceInformation.getReferenceList()) {
            refHolder.addReference(ref);
        }

        jScrollPane1.setViewportView(refHolder);
        refHolder.revalidate();
        jScrollPane1.revalidate();


        jPanel16.add(refAddPanel);
    }

    /**
     * Update the {@link ReferenceDefinitionHolder} and scroll to correct
     * position
     *
     * @param l The position
     */
    public void updateScrollPane(int l) {
        final int location = l;
        refHolder.revalidate();

        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                jScrollPane1.getViewport().repaint();

                JScrollBar scrollBar = jScrollPane1.getVerticalScrollBar();
                if (location == BOTTOM) {
                    scrollBar.setValue(scrollBar.getMaximum());
                } else if (location == TOP) {
                    scrollBar.setValue(scrollBar.getMinimum());
                } else if (location == LEAVE) {
                    // Was tun? Lassen?
                }
            }
        });
    }

    /**
     * Add the fields of the {@link ReferenceDefinitionAddPanel} to the given
     * {@link ReferenceDescription}
     *
     * @param refDef The reference description
     */
    public void setRefAddPanel(ReferenceDescription refDef) {
        refAddPanel.setFields(refDef);
    }

    /**
     * Get this dialogs {@link ReferenceDefinitionHolder}
     * @return The holder
     */
    public ReferenceDefinitionHolder getReferenceDefinitionHolder() {
        return refHolder;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        canclePropsButton = new javax.swing.JButton();
        savePropsButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel9.setBackground(new java.awt.Color(0, 102, 204));
        jPanel9.setPreferredSize(new java.awt.Dimension(100, 40));

        jLabel33.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/jmonitoring/References/Bundle"); // NOI18N
        jLabel33.setText(bundle.getString("ReferenceDefinitionDialog.jLabel33.text")); // NOI18N

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/question-frame.png"))); // NOI18N
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setFocusPainted(false);
        jButton7.setIconTextGap(0);
        jButton7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7help(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 383, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7)
                    .addComponent(jLabel33))
                .addContainerGap())
        );

        getContentPane().add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jPanel16.setPreferredSize(new java.awt.Dimension(560, 100));
        jPanel16.setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(381, 40));

        canclePropsButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        canclePropsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/cancel.png"))); // NOI18N
        canclePropsButton.setText(bundle.getString("ReferenceDefinitionDialog.canclePropsButton.text")); // NOI18N
        canclePropsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canclePropsButtonActionPerformed(evt);
            }
        });

        savePropsButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        savePropsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/accept.png"))); // NOI18N
        savePropsButton.setText(bundle.getString("ReferenceDefinitionDialog.savePropsButton.text")); // NOI18N
        savePropsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePropsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addComponent(canclePropsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(savePropsButton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savePropsButton)
                    .addComponent(canclePropsButton))
                .addContainerGap())
        );

        jPanel16.add(jPanel1, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel16, java.awt.BorderLayout.SOUTH);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(100, 300));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 300));
        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savePropsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePropsButtonActionPerformed
        if (MoniSoft.getInstance().ISTRIAL) {
            Messages.showMessage(MoniSoftConstants.DEMO, true);
            return;
        }
        ReferenceInformation.refreshReferences(refHolder.getIncludedReferences());
    }//GEN-LAST:event_savePropsButtonActionPerformed

    private void canclePropsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canclePropsButtonActionPerformed

        dispose();     }//GEN-LAST:event_canclePropsButtonActionPerformed

    private void jButton7help(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7help
        if (!ManualViewer.isShown) {
            ManualViewer viewer = new ManualViewer();
            viewer.showManual();
        }
        ManualViewer.goToPage(ManualBookmarks.DEFINE_REFERENCES.getPage());
    }//GEN-LAST:event_jButton7help
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton canclePropsButton;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton savePropsButton;
    // End of variables declaration//GEN-END:variables
}
