package de.jmonitoring.References;

import de.jmonitoring.Components.BuildingEditorDialog;
import de.jmonitoring.utils.UnitCalulation.UnitInformation;
import java.awt.Color;
import java.awt.Component;

/**
 * This panel represents a single {@link ReferenceValue} to be place in a
 * {@link ReferenceItemHolder}
 *
 * @author togro
 */
public class ReferenceItem extends javax.swing.JPanel {

    private final BuildingEditorDialog caller;
    private final ReferenceValue reference;

    /**
     * Creatze a new panel useing the given {@link ReferenceValue}
     *
     * @param reference The {@link ReferenceValue}for this panel
     * @param caller The calling {@link BuildingEditorDialog}
     */
    public ReferenceItem(ReferenceValue reference, BuildingEditorDialog caller) {
        this.caller = caller;
        this.reference = reference;
        initComponents();
        if (this.reference != null) {
            nameLabel.setText(this.reference.getName());
            valueLabel.setText(String.valueOf(this.reference.getValue())); // TODO mit Decimalformat!
            unitLabel.setText(UnitInformation.getUnitNameFromID(ReferenceInformation.getUnitIDForReference(this.reference.getName())));
            if (caller != null) {
                jButton1.setEnabled(caller.isEditable());
            }
        }
    }

    /**
     * Return this panels {@link ReferenceValue}
     *
     * @return The {@link ReferenceValue}
     */
    public ReferenceValue getReference() {
        return this.reference;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        unitLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(185, 204, 204));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        nameLabel.setText("Name");

        valueLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        valueLabel.setText("Wert");

        unitLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        unitLabel.setText("Einheit");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/cross.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setPreferredSize(new java.awt.Dimension(20, 20));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(nameLabel)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addComponent(valueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addComponent(unitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Löschen der Referenz aus der Liste
        Component c = getParent();
        while (!(c instanceof ReferenceItemHolder)) {
            c = c.getParent();
        }
        ((ReferenceItemHolder) c).removeReference(this);
}//GEN-LAST:event_jButton1ActionPerformed

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        setBackground(Color.YELLOW);
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        setBackground(new Color(185, 204, 204));
    }//GEN-LAST:event_formMouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        caller.setRefAddPanel(this.reference);
    }//GEN-LAST:event_formMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel unitLabel;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
