package de.jmonitoring.References;

import de.jmonitoring.Components.BuildingEditorDialog;
import de.jmonitoring.utils.UnitCalulation.UnitInformation;
import de.jmonitoring.utils.textfields.ConvertStringToDouble;
import de.jmonitoring.utils.textfields.DoubleTextField;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 * This Panel can be used to define a new reference value for a building in the
 * {@link BuildingEditorDialog}
 *
 * @author togro
 */
public class ReferenceAddPanel extends javax.swing.JPanel {

    private final BuildingEditorDialog caller;

    /**
     * Creates new form ReferenceAddPanel
     *
     * @param editable Determine if this dialog is view only or editable
     * @param bd The calling {@link BuildingEditorDialog}
     */
    public ReferenceAddPanel(boolean editable, BuildingEditorDialog bd) {
        initComponents();
        this.caller = bd;
        valueTextField.setEnabled(editable);
        referencesCombobox.setEnabled(editable);
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (ReferenceDescription ref : ReferenceInformation.getReferenceList()) {
            model.addElement(ref.getName());
        }
        referencesCombobox.setModel(model);

        unitLabel.setText(UnitInformation.getUnitNameFromID(ReferenceInformation.getUnitIDForReference(((String) referencesCombobox.getSelectedItem()))));
    }

    /**
     * Set the fields according to the given {@link ReferenceValue}
     *
     * @param reference The reference value
     */
    public void setFields(ReferenceValue reference) {
        referencesCombobox.setSelectedItem(reference.getName());
        valueTextField.setText(String.valueOf(reference.getValue()));
    }

    /**
     * Build a {@link ReferenceValue} out of the dialogs fields
     *
     * @return The new {@link ReferenceValue} 
     */
    public ReferenceValue getReferenceFields() {
        // Prüfen ob gültiger Wert > 0
        if (valueTextField.getText().trim().isEmpty() || new ConvertStringToDouble().convert(valueTextField.getText()) <= 0d) {
            return null;
        }

        Integer buildingID;
        if (caller.getCurrentProperties().getBuildingID() == 0) {
            buildingID = null;
        } else {
            buildingID = caller.getCurrentProperties().getBuildingID();
        }

        return new ReferenceValue((String) referencesCombobox.getSelectedItem(), new ConvertStringToDouble().convert(valueTextField.getText()), buildingID, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        valueTextField = new DoubleTextField();
        jButton1 = new javax.swing.JButton();
        referencesCombobox = new javax.swing.JComboBox();
        unitLabel = new javax.swing.JLabel();

        nameLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/jmonitoring/References/Bundle"); // NOI18N
        nameLabel.setText(bundle.getString("ReferenceAddPanel.nameLabel.text")); // NOI18N

        valueLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        valueLabel.setText(bundle.getString("ReferenceAddPanel.valueLabel.text")); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/add.png"))); // NOI18N
        jButton1.setToolTipText(bundle.getString("ReferenceAddPanel.jButton1.toolTipText")); // NOI18N
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.setMaximumSize(new java.awt.Dimension(25, 25));
        jButton1.setMinimumSize(new java.awt.Dimension(25, 25));
        jButton1.setPreferredSize(new java.awt.Dimension(25, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        referencesCombobox.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        referencesCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        referencesCombobox.setMinimumSize(new java.awt.Dimension(71, 19));
        referencesCombobox.setPreferredSize(new java.awt.Dimension(71, 19));
        referencesCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                referencesComboboxActionPerformed(evt);
            }
        });

        unitLabel.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        unitLabel.setText(bundle.getString("ReferenceAddPanel.unitLabel.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(referencesCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(valueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unitLabel))
                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(nameLabel)
                    .addComponent(valueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(referencesCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unitLabel))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (getReferenceFields() != null) { // wenn es eine gültige Bezugsgröße ist
            caller.getReferenceItemHolder().addReference(getReferenceFields());
            caller.updateScrollPane(BuildingEditorDialog.BOTTOM);
        } else { // sonst warnen
            JOptionPane.showMessageDialog(this, java.util.ResourceBundle.getBundle("de/jmonitoring/Components/Bundle").getString("ReferenceAddPanel.NOREFVALUEMSG"), java.util.ResourceBundle.getBundle("de/jmonitoring/Components/Bundle").getString("ReferenceAddPanel.NOREFVALUE"), JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void referencesComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_referencesComboboxActionPerformed
        unitLabel.setText(UnitInformation.getUnitNameFromID(ReferenceInformation.getUnitIDForReference(((String) referencesCombobox.getSelectedItem()))));
    }//GEN-LAST:event_referencesComboboxActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JComboBox referencesCombobox;
    private javax.swing.JLabel unitLabel;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTextField valueTextField;
    // End of variables declaration//GEN-END:variables
}
