package de.jmonitoring.utils.UnitCalulation;

import de.jmonitoring.help.ManualBookmarks;
import de.jmonitoring.help.ManualViewer;
import javax.swing.JScrollBar;
import javax.swing.SwingUtilities;

/**
 * This is the main dialog window for editing units<p> It hold a
 * {@link UnitDefinitionHolder} that itself holds each
 * {@link UnitDefinitionItem}.
 *
 * @author togro
 */
public class UnitDefinitionDialog extends javax.swing.JDialog {

    private final UnitDefinitionHolder unitHolder;
    private UnitDefinitionAddPanel unitAddPanel = new UnitDefinitionAddPanel(true, this);
    public static final int TOP = 0;
    public static final int BOTTOM = 1;
    public static final int LEAVE = 2;

    /**
     * Creates new form ReferenceDefinitionDialog
     *
     * @param parent The parent of this frame
     * @param modal if true this frame is model
     */
    public UnitDefinitionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        unitHolder = new UnitDefinitionHolder(true, this);
        set();
    }

    /**
     * Fills the {@link UnitDefinitionHolder} with all known Units from the
     * global unit list.
     */
    private void set() {
        for (Unit unit : UnitInformation.getUnitList().values()) {
            unitHolder.addUnit(unit);
        }

        jScrollPane1.setViewportView(unitHolder);
        unitHolder.revalidate();
        jScrollPane1.revalidate();

        lowerPanel.add(unitAddPanel);
    }

    /**
     * Refresh {@link ReferenceItemHolder} and move scrollpane to the given
     * lovation
     *
     * @param loc The location to move to (top/bottom/leave)
     */
    public void updateScrollPane(int loc) {
        final int location = loc;
        unitHolder.revalidate();

        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                jScrollPane1.getViewport().repaint();

                JScrollBar scrollBar = jScrollPane1.getVerticalScrollBar();
                if (location == BOTTOM) {
                    scrollBar.setValue(scrollBar.getMaximum());
                } else if (location == TOP) {
                    scrollBar.setValue(scrollBar.getMinimum());
                } else if (location == LEAVE) {
                    // nothinfg to do?
                }
            }
        });
    }

    /**
     * Set the field of the input panel to the settign of the given
     * {@link Unit}.
     *
     * @param unit The unit
     */
    public void setUnitAddPanel(Unit unit) {
        unitAddPanel.setFields(unit);
    }

    public UnitDefinitionHolder getUnitDefinitionHolder() {
        return unitHolder;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lowerPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        canclePropsButton = new javax.swing.JButton();
        savePropsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel9.setBackground(new java.awt.Color(0, 102, 204));
        jPanel9.setPreferredSize(new java.awt.Dimension(100, 40));

        jLabel33.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/jmonitoring/Components/Bundle"); // NOI18N
        jLabel33.setText(bundle.getString("UnitDefinitionDialog.jLabel33.text")); // NOI18N

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/question-frame.png"))); // NOI18N
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setFocusPainted(false);
        jButton7.setIconTextGap(0);
        jButton7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7help(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 348, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton7)
                    .addComponent(jLabel33))
                .addContainerGap())
        );

        getContentPane().add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(100, 300));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 300));
        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        lowerPanel.setPreferredSize(new java.awt.Dimension(560, 100));
        lowerPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(381, 30));

        canclePropsButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        canclePropsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/cancel.png"))); // NOI18N
        canclePropsButton.setText(bundle.getString("UnitDefinitionDialog.canclePropsButton.text")); // NOI18N
        canclePropsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canclePropsButtonActionPerformed(evt);
            }
        });

        savePropsButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        savePropsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/accept.png"))); // NOI18N
        savePropsButton.setText(bundle.getString("UnitDefinitionDialog.savePropsButton.text")); // NOI18N
        savePropsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePropsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(308, Short.MAX_VALUE)
                .addComponent(canclePropsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(savePropsButton)
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savePropsButton)
                    .addComponent(canclePropsButton))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        lowerPanel.add(jPanel1, java.awt.BorderLayout.SOUTH);

        getContentPane().add(lowerPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savePropsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePropsButtonActionPerformed
        UnitInformation.refreshUnits(unitHolder.getIncludedUnits());
        dispose();
    }//GEN-LAST:event_savePropsButtonActionPerformed

    private void canclePropsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canclePropsButtonActionPerformed

        dispose();     }//GEN-LAST:event_canclePropsButtonActionPerformed

    private void jButton7help(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7help
        if (!ManualViewer.isShown) {
            ManualViewer viewer = new ManualViewer();
            viewer.showManual();
        }
        ManualViewer.goToPage(ManualBookmarks.UNIT_DIALOG.getPage());
    }//GEN-LAST:event_jButton7help
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton canclePropsButton;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel lowerPanel;
    private javax.swing.JButton savePropsButton;
    // End of variables declaration//GEN-END:variables
}
