package de.jmonitoring.utils.UnitCalulation;

import java.awt.Component;
import java.util.ArrayList;
import org.jdesktop.swingx.VerticalLayout;

/**
 * This panel holds multiple {@link UnitDefinitionItem}s and defines methods to
 * remove, add and retrieve them.
 *
 * @author togro
 */
public class UnitDefinitionHolder extends javax.swing.JPanel {

    private final UnitDefinitionDialog caller;

    /**
     * Creates new form ReferenceItemHolder
     *
     * @param editable If fale this panel is locked
     * @param caller The parent of this holder
     */
    public UnitDefinitionHolder(boolean editable, UnitDefinitionDialog caller) {
        this.caller = caller;
        initComponents();
        setLayout(new VerticalLayout(2));
    }

    /**
     * Creates a {@link UnitDefinitionItem} from the given unit and adds it to
     * the {@link UnitDefinitionHolder}
     *
     * @param unit The unit
     */
    public void addUnit(Unit unit) {
        for (Component c : getComponents()) {
            if (c instanceof UnitDefinitionItem) {
                if (((UnitDefinitionItem) c).getUnit().getUnit().equals(unit.getUnit())) {
                    remove(c);
                }
            }
        }
        add(new UnitDefinitionItem(unit, this.caller)); // Bezugsgröße hinzufügen
    }

    /**
     * Deletes a unit and updates the scrollpane
     *
     * @param item The unit item to remove
     */
    public void removeUnit(UnitDefinitionItem item) {
//        deletedUnits.add(item.getUnit());
        remove(item);
        this.caller.updateScrollPane(UnitDefinitionDialog.LEAVE);
    }

    /**
     * Return the units in the {@link UnitDefinitionHolder}
     *
     * @return The list of units
     */
    public ArrayList<Unit> getIncludedUnits() {
        ArrayList<Unit> list = new ArrayList<Unit>();
        for (Component c : getComponents()) {
            if (c instanceof UnitDefinitionItem) {
                list.add(((UnitDefinitionItem) c).getUnit());
            }
        }
        return list;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 204));
        setMinimumSize(new java.awt.Dimension(400, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
