/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CompareValueMappingEditor.java
 *
 * Created on 22.03.2010, 16:20:02
 */
package de.jmonitoring.Components;

import de.jmonitoring.SensorCollectionHandling.SensorCollectionPanel;
import de.jmonitoring.SensorCategoryHandling.NestedSetTransfer;
import de.jmonitoring.SensorCollectionHandling.SensorCollectionHandler;
import de.jmonitoring.base.sensors.SensorInformation;
import de.jmonitoring.base.sensors.SensorProperties;
import de.jmonitoring.SensorCollectionHandling.SensorCollection;
import de.jmonitoring.SensorCategoryHandling.NestedSet;
import de.jmonitoring.SensorCategoryHandling.SensorJtree;
import de.jmonitoring.SensorCategoryHandling.SensorTreeCellRenderer;
import de.jmonitoring.SensorCategoryHandling.SensorTreeModels;
import de.jmonitoring.help.ManualBookmarks;
import de.jmonitoring.help.ManualViewer;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.SwingUtilities;
import javax.swing.tree.DefaultTreeSelectionModel;
import javax.swing.tree.TreeModel;
import javax.swing.tree.TreeNode;
import javax.swing.tree.TreePath;
import javax.swing.tree.TreeSelectionModel;
import org.jdesktop.swingx.VerticalLayout;

/**
 *
 * @author togro
 */
public class CompareValueMappingEditor extends javax.swing.JDialog {

    private boolean changed = false;
    private boolean active = false;
    private ArrayList<String> collectionDeleteList = new ArrayList<String>();
    private HashMap<String, Integer> renamedNames = new HashMap<String, Integer>();

    /**
     * Creates new form CompareValueMappingEditor
     */
    public CompareValueMappingEditor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(900, 700);
        setModalityType(ModalityType.APPLICATION_MODAL);
        tree.setModel(SensorTreeModels.buildingTreeModel());
        TreeSelectionModel tsm = new DefaultTreeSelectionModel();
        tsm.setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        tree.setSelectionModel(tsm);
        tree.setCellRenderer(new SensorTreeCellRenderer());
        tree.setShowsRootHandles(true);

        populateGroupList();
        doCascade(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tree = new SensorJtree();
        jPanel7 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        entryHolder = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 102, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(756, 46));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/jmonitoring/Components/Bundle"); // NOI18N
        jLabel6.setText(bundle.getString("CompareValueMappingEditor.jLabel6.text")); // NOI18N

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/question-frame.png"))); // NOI18N
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setFocusPainted(false);
        jButton7.setIconTextGap(0);
        jButton7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7help(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 556, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.NORTH);

        jSplitPane1.setDividerLocation(350);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("CompareValueMappingEditor.jPanel4.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 9))); // NOI18N
        jPanel4.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel4.setLayout(new java.awt.BorderLayout());

        buttonGroup1.add(jToggleButton5);
        jToggleButton5.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/edit-hyphenation.png"))); // NOI18N
        jToggleButton5.setText(bundle.getString("CompareValueMappingEditor.jToggleButton5.text")); // NOI18N
        jToggleButton5.setIconTextGap(0);
        jToggleButton5.setMargin(new java.awt.Insets(2, 2, 2, 0));
        jToggleButton5.setMaximumSize(new java.awt.Dimension(0, 19));
        jToggleButton5.setMinimumSize(new java.awt.Dimension(0, 19));
        jToggleButton5.setPreferredSize(new java.awt.Dimension(80, 19));
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton4);
        jToggleButton4.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/bank.png"))); // NOI18N
        jToggleButton4.setText(bundle.getString("CompareValueMappingEditor.jToggleButton4.text")); // NOI18N
        jToggleButton4.setIconTextGap(0);
        jToggleButton4.setMargin(new java.awt.Insets(2, 2, 2, 0));
        jToggleButton4.setMaximumSize(new java.awt.Dimension(0, 19));
        jToggleButton4.setMinimumSize(new java.awt.Dimension(0, 19));
        jToggleButton4.setPreferredSize(new java.awt.Dimension(80, 19));
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton2);
        jToggleButton2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/price-tag-label.png"))); // NOI18N
        jToggleButton2.setText(bundle.getString("CompareValueMappingEditor.jToggleButton2.text")); // NOI18N
        jToggleButton2.setIconTextGap(0);
        jToggleButton2.setMargin(new java.awt.Insets(2, 2, 2, 0));
        jToggleButton2.setMaximumSize(new java.awt.Dimension(0, 19));
        jToggleButton2.setMinimumSize(new java.awt.Dimension(0, 19));
        jToggleButton2.setPreferredSize(new java.awt.Dimension(80, 19));
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton1);
        jToggleButton1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/edit-symbol.png"))); // NOI18N
        jToggleButton1.setText(bundle.getString("CompareValueMappingEditor.jToggleButton1.text")); // NOI18N
        jToggleButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jToggleButton1.setIconTextGap(1);
        jToggleButton1.setMargin(new java.awt.Insets(2, 2, 2, 0));
        jToggleButton1.setMaximumSize(new java.awt.Dimension(0, 19));
        jToggleButton1.setMinimumSize(new java.awt.Dimension(0, 19));
        jToggleButton1.setPreferredSize(new java.awt.Dimension(80, 19));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton7);
        jToggleButton7.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jToggleButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/puzzle.png"))); // NOI18N
        jToggleButton7.setText(bundle.getString("CompareValueMappingEditor.jToggleButton7.text")); // NOI18N
        jToggleButton7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jToggleButton7.setIconTextGap(0);
        jToggleButton7.setMargin(new java.awt.Insets(2, 2, 2, 0));
        jToggleButton7.setMaximumSize(new java.awt.Dimension(0, 19));
        jToggleButton7.setMinimumSize(new java.awt.Dimension(0, 19));
        jToggleButton7.setPreferredSize(new java.awt.Dimension(80, 19));
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton6);
        jToggleButton6.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/edit-rule.png"))); // NOI18N
        jToggleButton6.setText(bundle.getString("CompareValueMappingEditor.jToggleButton6.text")); // NOI18N
        jToggleButton6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jToggleButton6.setIconTextGap(0);
        jToggleButton6.setMargin(new java.awt.Insets(2, 2, 2, 0));
        jToggleButton6.setMaximumSize(new java.awt.Dimension(0, 19));
        jToggleButton6.setMinimumSize(new java.awt.Dimension(0, 19));
        jToggleButton6.setPreferredSize(new java.awt.Dimension(80, 19));
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton3);
        jToggleButton3.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/block.png"))); // NOI18N
        jToggleButton3.setText(bundle.getString("CompareValueMappingEditor.jToggleButton3.text")); // NOI18N
        jToggleButton3.setIconTextGap(0);
        jToggleButton3.setMargin(new java.awt.Insets(2, 2, 2, 0));
        jToggleButton3.setMaximumSize(new java.awt.Dimension(0, 19));
        jToggleButton3.setMinimumSize(new java.awt.Dimension(0, 19));
        jToggleButton3.setPreferredSize(new java.awt.Dimension(80, 19));
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "KAT" }));
        jComboBox1.setEnabled(false);

        tree.setToolTipText(bundle.getString("CompareValueMappingEditor.tree.toolTipText")); // NOI18N
        tree.setDragEnabled(true);
        jScrollPane1.setViewportView(tree);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(jToggleButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(jToggleButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(jToggleButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(297, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel7.setPreferredSize(new java.awt.Dimension(411, 26));

        jButton5.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/expand.png"))); // NOI18N
        jButton5.setToolTipText(bundle.getString("CompareValueMappingEditor.jButton5.toolTipText")); // NOI18N
        jButton5.setMaximumSize(new java.awt.Dimension(23, 23));
        jButton5.setMinimumSize(new java.awt.Dimension(23, 23));
        jButton5.setPreferredSize(new java.awt.Dimension(23, 23));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/collapse.png"))); // NOI18N
        jButton6.setToolTipText(bundle.getString("CompareValueMappingEditor.jButton6.toolTipText")); // NOI18N
        jButton6.setMaximumSize(new java.awt.Dimension(23, 23));
        jButton6.setMinimumSize(new java.awt.Dimension(23, 23));
        jButton6.setPreferredSize(new java.awt.Dimension(23, 23));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(422, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel7, java.awt.BorderLayout.SOUTH);

        jSplitPane1.setRightComponent(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("CompareValueMappingEditor.jPanel5.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 9))); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(92, 300));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel8.setMaximumSize(new java.awt.Dimension(32767, 26));
        jPanel8.setOpaque(false);

        jButton3.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/add.png"))); // NOI18N
        jButton3.setText(bundle.getString("CompareValueMappingEditor.jButton3.text")); // NOI18N
        jButton3.setMaximumSize(new java.awt.Dimension(26, 24));
        jButton3.setMinimumSize(new java.awt.Dimension(26, 24));
        jButton3.setPreferredSize(new java.awt.Dimension(26, 24));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/expand.png"))); // NOI18N
        jButton8.setToolTipText(bundle.getString("CompareValueMappingEditor.jButton8.toolTipText")); // NOI18N
        jButton8.setMaximumSize(new java.awt.Dimension(23, 23));
        jButton8.setMinimumSize(new java.awt.Dimension(23, 23));
        jButton8.setPreferredSize(new java.awt.Dimension(23, 23));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/collapse.png"))); // NOI18N
        jButton9.setMaximumSize(new java.awt.Dimension(23, 23));
        jButton9.setMinimumSize(new java.awt.Dimension(23, 23));
        jButton9.setPreferredSize(new java.awt.Dimension(23, 23));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel5.add(jPanel8, java.awt.BorderLayout.SOUTH);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        entryHolder.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        entryHolder.setMinimumSize(new java.awt.Dimension(0, 0));
        entryHolder.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout entryHolderLayout = new javax.swing.GroupLayout(entryHolder);
        entryHolder.setLayout(entryHolderLayout);
        entryHolderLayout.setHorizontalGroup(
            entryHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );
        entryHolderLayout.setVerticalGroup(
            entryHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );

        entryHolder.setLayout(new VerticalLayout(2));
        jScrollPane2.setViewportView(entryHolder);
        entryHolder.getAccessibleContext().setAccessibleName("");

        //jScrollPane2.setViewportView(compareList);
        jPanel5.add(jScrollPane2, java.awt.BorderLayout.CENTER);
        jScrollPane2.getAccessibleContext().setAccessibleName("");

        jSplitPane1.setLeftComponent(jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(756, 30));

        saveButton.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/disk.png"))); // NOI18N
        saveButton.setText(bundle.getString("CompareValueMappingEditor.saveButton.text")); // NOI18N
        saveButton.setEnabled(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/cancel.png"))); // NOI18N
        cancelButton.setText(bundle.getString("CompareValueMappingEditor.cancelButton.text")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(619, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7help(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7help
        if (!ManualViewer.isShown) {
            ManualViewer viewer = new ManualViewer();
            viewer.showManual();
        }
        ManualViewer.goToPage(ManualBookmarks.COMPARE_VALUE_MAPPING.getPage());
}//GEN-LAST:event_jButton7help

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        TreeModel model = SensorTreeModels.unitTreeModel();
        tree.setModel(model);
}//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        TreeModel model = SensorTreeModels.typeTreeModel();
        tree.setModel(model);
}//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        TreeModel model = SensorTreeModels.buildingTreeModel();
        tree.setModel(model);
}//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        TreeModel model = SensorTreeModels.alphabeticTreeModel();
        tree.setModel(model);
}//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        TreeModel model = SensorTreeModels.mediumTreeModel();
        tree.setModel(model);
}//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        TreeModel model = SensorTreeModels.flatTreeModel();
        tree.setModel(model);
}//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        tree.setModel(new NestedSet().getTreeModelFromNestedSet(NestedSetTransfer.readNestedSetFromDB(jComboBox1.getSelectedItem().toString())));
}//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        expandAll(tree, new TreePath((TreeNode) tree.getModel().getRoot()), true);
}//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        expandAll(tree, new TreePath((TreeNode) tree.getModel().getRoot()), false);
}//GEN-LAST:event_jButton6ActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        if (changed) {
            if (JOptionPane.showConfirmDialog(this, java.util.ResourceBundle.getBundle("de/jmonitoring/Components/Bundle").getString("CompareValueMappingEditor.REALLYCANCEL"), java.util.ResourceBundle.getBundle("de/jmonitoring/Components/Bundle").getString("CompareValueMappingEditor.FRAGE"), JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                dispose();
            }
        } else {
            dispose();
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String name = JOptionPane.showInputDialog(this, java.util.ResourceBundle.getBundle("de/jmonitoring/Components/Bundle").getString("CompareValueMappingEditor.BITTE GEBEN SIE EINE BEZEICHUNG FÜR DIE NEUE VERGLEICHSGRUPPE AN"), java.util.ResourceBundle.getBundle("de/jmonitoring/Components/Bundle").getString("CompareValueMappingEditor.NEUE VERGLEICHSGRUPPE"), JOptionPane.QUESTION_MESSAGE);
        if (name != null && !name.isEmpty()) {
            addEntry(new SensorCollection(name));
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        HashSet<SensorProperties> sensorProperties;
        String collectionName;

        // delete collections
        for (String deleteName : collectionDeleteList) {
//            System.out.println("deleting collection: " + deleteName);
            SensorCollectionHandler.removeCollection(deleteName, false);
        }
        SensorCollectionHandler.refreshCollections();
        collectionDeleteList.clear();

        // loop all Sensorcollections 
        for (int i = 0; i < entryHolder.getComponentCount(); i++) {
            collectionName = ((SensorCollectionPanel) entryHolder.getComponent(i)).getTitle();

            // get all sensors in current collection
            HashSet<Integer> list = new HashSet<Integer>();
            sensorProperties = ((SensorCollection) ((SensorCollectionPanel) entryHolder.getComponent(i)).getCompareValue()).getPropertySet();

            // loop all sensors in current collection
            for (SensorProperties p : sensorProperties) {
                list.add(p.getSensorID()); // und die SensorProperties in Liste aufnehmen
            }
            Integer collectionID = SensorCollectionHandler.getCollectionID(collectionName);
            if (collectionID != null || renamedNames.containsKey(collectionName)) { // a collection with that name already exists or it was renamed: update it
                if (collectionID == null) {
                    collectionID = renamedNames.get(collectionName);
                }
                SensorCollectionHandler.updateCollection(collectionID, collectionName, list, ((SensorCollectionPanel) entryHolder.getComponent(i)).isClimateCorrectable(), false);
            } else { // this is a new collection: create it
                SensorCollectionHandler.insertCollection(collectionName, list, SensorCollectionHandler.COMPARE_COLLECTION, ((SensorCollectionPanel) entryHolder.getComponent(i)).isClimateCorrectable(), false);
            }
        }
        changed = false;
        saveButton.setEnabled(false);
        dispose();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        doCascade(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // alle einklappen
        doCascade(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * Für eine neue Verbrauchskategorie zur Liste hinzu
     *
     * @param cv
     */
    private void addEntry(SensorCollection cv) {
        // Prüfen ob Name schon vorhanden....
        for (int i = 0; i < entryHolder.getComponentCount(); i++) {
            if (cv.getName().equals(((SensorCollection) ((SensorCollectionPanel) entryHolder.getComponent(i)).getCompareValue()).getName())) {
                JOptionPane.showMessageDialog(this, java.util.ResourceBundle.getBundle("de/jmonitoring/Components/Bundle").getString("CompareValueMappingEditor.EINE VERBRAUCHSGRUPPE MIT DIESEM NAMEN IST BEREITS VORHADEN."));
                return;
            }
        }

        // Wenn nicht vorhanden neues Panel bilden und hinzufügen
        SensorCollectionPanel entryPanel = new SensorCollectionPanel(cv, SensorCollectionHandler.COMPARE_COLLECTION); // neues Panel erzeugen
        entryPanel.initSensors(jScrollPane2, true);
//        entryPanel.sort();
        entryHolder.add(entryPanel);
        entryHolder.doLayout();
        entryHolder.revalidate();
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                jScrollPane2.getVerticalScrollBar().setValue(jScrollPane2.getVerticalScrollBar().getModel().getMinimum());
            }
        });
        jScrollPane2.revalidate();

        if (active) {
            changed = true;
            saveButton.setEnabled(true);
        }
    }

    public void doCascade(boolean b) {
        // alle einklappen
        for (int i = 0; i < entryHolder.getComponentCount(); i++) {
            ((SensorCollectionPanel) entryHolder.getComponent(i)).doCascade(b);
        }
    }

    public void removeEntry(SensorCollectionPanel panel) {
        entryHolder.remove(panel);
        collectionDeleteList.add(panel.getTitle());
        panel = null;
        entryHolder.doLayout();
        entryHolder.revalidate();
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                jScrollPane2.getVerticalScrollBar().setValue(jScrollPane2.getVerticalScrollBar().getModel().getMinimum());
            }
        });
        jScrollPane2.revalidate();
        if (active) {
            changed = true;
            saveButton.setEnabled(true);
        }
    }

    public void setChangedState(boolean b) {
        changed = b;
        saveButton.setEnabled(b);
    }

    public void renameCollection(String oldName, String newName) {
        if (SensorCollectionHandler.getCollectionID(oldName) != null) {
            renamedNames.put(newName, SensorCollectionHandler.getCollectionID(oldName));
        }
    }

    /**
     * Belegt die Kategorienliste mit den kategorien aus der DB
     */
    private void populateGroupList() {
        Map<String, ArrayList<Integer>> map = SensorCollectionHandler.getCollectionsOfCreator(SensorCollectionHandler.COMPARE_COLLECTION);
        Iterator<String> it = map.keySet().iterator();
        String name;
        ArrayList<Integer> list;
        SensorCollection cv;
        while (it.hasNext()) {
            name = it.next();
            cv = new SensorCollection(name);
            list = map.get(name);
            for (Integer id : list) {
                cv.addSensor(SensorInformation.getSensorProperties(id));
            }
            addEntry(cv);
        }
        jScrollPane2.revalidate();
        active = true;
    }

    /**
     *
     * @param tree
     * @param parent
     * @param expand
     */
    private void expandAll(JTree tree, TreePath parent, boolean expand) {
        // Traverse children
        TreeNode node = (TreeNode) parent.getLastPathComponent();
        if (node.getChildCount() >= 0) {
            for (Enumeration e = node.children(); e.hasMoreElements();) {
                TreeNode n = (TreeNode) e.nextElement();
                TreePath path = parent.pathByAddingChild(n);
                expandAll(tree, path, expand);
            }
        }

        // Expansion or collapse must be done bottom-up
        if (expand) {
            tree.expandPath(parent);
        } else {
            tree.collapsePath(parent);
        }
        jScrollPane2.revalidate();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel entryHolder;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JButton saveButton;
    private javax.swing.JTree tree;
    // End of variables declaration//GEN-END:variables
}
