/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DateChooserPanel.java
 *
 * Created on 30.11.2009, 12:28:12
 */
package de.jmonitoring.Components;

import java.util.Calendar;
import java.util.Date;

import javax.swing.JPanel;
import javax.swing.JToggleButton;

import com.toedter.calendar.JDateChooser;

import de.jmonitoring.base.MainApplication;
import de.jmonitoring.utils.intervals.DateInterval;

/**
 *
 * @author togro
 */
public class DatePanel extends JPanel {

    private final static int TODAY = 0;
    private final static int YESTERDAY = 1;
    private final static int LASTWEEK = 2;
    private final static int LASTMONTH = 3;
    private final MainApplication gui;

    /**
     * Creates new form DateChooserPanel
     */
    public DatePanel(MainApplication gui, boolean showLock) {
        super();
        this.gui = gui;
        initComponents();
        startDateChooser.getJCalendar().setTodayButtonVisible(true);
        endDateChooser.getJCalendar().setTodayButtonVisible(true);
        DateToggle.setVisible(showLock);
    }

    public JDateChooser getStartDateChooser() {
        return startDateChooser;
    }

    public JDateChooser getEndDateChooser() {
        return endDateChooser;
    }

    public boolean isLockDate() {
        return DateToggle.isSelected();
    }

    public Date getStartDate() {
        return startDateChooser.getDate();
    }

    public void setStartDate(Date d) {
        startDateChooser.setDate(d);
    }

    public Date getEndDate() {
        return endDateChooser.getDate();
    }

    public void setEndDate(Date d) {
        endDateChooser.setDate(d);
    }

    public JToggleButton getLockToggle() {
        return DateToggle;
    }

    public DateInterval getInterval() {
        DateInterval result = new DateInterval();
        result.setStartDate(getStartDate());
        result.setEndDate(getEndDate());
        return result;
    }

    public void setInterval(DateInterval interval) {
        setStartDate(interval.getStartDate());
        setEndDate(interval.getEndDate());
    }

    private void setDateChooser(JDateChooser start, JDateChooser end, int span) {
        Calendar cal = Calendar.getInstance();
        switch (span) {
            case TODAY:
                start.setDate(new Date());
                end.setDate(new Date());
                break;
            case YESTERDAY:
                cal = Calendar.getInstance();
                cal.add(Calendar.DATE, -1);
                start.setDate(cal.getTime());
                end.setDate(cal.getTime());
                break;
            case LASTWEEK:
                cal = Calendar.getInstance();
                cal.add(Calendar.DATE, -7);
                start.setDate(cal.getTime());
                cal.add(Calendar.DATE, 6);
                end.setDate(cal.getTime());
                break;
            case LASTMONTH:
                cal = Calendar.getInstance();
                cal.add(Calendar.MONTH, -1);
                cal.set(Calendar.DAY_OF_MONTH, cal.getActualMinimum(Calendar.DAY_OF_MONTH));
                start.setDate(cal.getTime());
                cal.set(Calendar.DAY_OF_MONTH, cal.getActualMaximum(Calendar.DAY_OF_MONTH));
                end.setDate(cal.getTime());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startDateChooser = new com.toedter.calendar.JDateChooser();
        endDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        DateToggle = new javax.swing.JToggleButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/jmonitoring/Components/Bundle"); // NOI18N
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), bundle.getString("DatePanel.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 9), new java.awt.Color(0, 0, 0))); // NOI18N
        setMaximumSize(new java.awt.Dimension(32767, 70));
        setMinimumSize(new java.awt.Dimension(467, 70));
        setPreferredSize(new java.awt.Dimension(467, 70));

        startDateChooser.setToolTipText(bundle.getString("DatePanel.startDateChooser.toolTipText")); // NOI18N
        startDateChooser.setDateFormatString(bundle.getString("DatePanel.DateFormatString")); // NOI18N
        startDateChooser.setDoubleBuffered(false);
        startDateChooser.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        startDateChooser.setMaxSelectableDate(null);
        startDateChooser.setMinSelectableDate(null);

        endDateChooser.setDateFormatString(bundle.getString("DatePanel.DateFormatString")); // NOI18N
        endDateChooser.setDoubleBuffered(false);
        endDateChooser.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel4.setText(bundle.getString("DatePanel.jLabel4.text")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel5.setText(bundle.getString("DatePanel.jLabel5.text")); // NOI18N

        jPanel7.setMaximumSize(new java.awt.Dimension(166, 46));
        jPanel7.setMinimumSize(new java.awt.Dimension(166, 46));
        jPanel7.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        jButton11.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jButton11.setText(bundle.getString("DatePanel.jButton11.text")); // NOI18N
        jButton11.setToolTipText(bundle.getString("DatePanel.jButton11.toolTipText")); // NOI18N
        jButton11.setFocusable(false);
        jButton11.setMargin(new java.awt.Insets(2, 1, 2, 0));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton11);

        jButton1.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jButton1.setText(bundle.getString("DatePanel.jButton1.text")); // NOI18N
        jButton1.setToolTipText(bundle.getString("DatePanel.jButton1.toolTipText")); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setMargin(new java.awt.Insets(2, 1, 2, 0));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1);

        jButton10.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jButton10.setText(bundle.getString("DatePanel.jButton10.text")); // NOI18N
        jButton10.setToolTipText(bundle.getString("DatePanel.jButton10.toolTipText")); // NOI18N
        jButton10.setFocusable(false);
        jButton10.setMargin(new java.awt.Insets(2, 1, 2, 0));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton10);

        jButton12.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jButton12.setText(bundle.getString("DatePanel.jButton12.text")); // NOI18N
        jButton12.setToolTipText(bundle.getString("DatePanel.jButton12.toolTipText")); // NOI18N
        jButton12.setFocusable(false);
        jButton12.setMargin(new java.awt.Insets(2, 1, 2, 0));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton12);

        DateToggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/lock-unlock.png"))); // NOI18N
        DateToggle.setToolTipText(bundle.getString("DatePanel.DateToggle.toolTipText")); // NOI18N
        DateToggle.setBorder(null);
        DateToggle.setBorderPainted(false);
        DateToggle.setContentAreaFilled(false);
        DateToggle.setFocusPainted(false);
        DateToggle.setFocusable(false);
        DateToggle.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/lock.png"))); // NOI18N
        DateToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateToggleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(endDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DateToggle)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(startDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(endDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)))
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DateToggle))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        setDateChooser(startDateChooser, endDateChooser, TODAY);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        setDateChooser(startDateChooser, endDateChooser, YESTERDAY);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setDateChooser(startDateChooser, endDateChooser, LASTWEEK);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        setDateChooser(startDateChooser, endDateChooser, LASTMONTH);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void DateToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateToggleActionPerformed
        System.out.println("lock");
        this.gui.lockDates(DateToggle.isSelected());        // TODO add your handling code here:
    }//GEN-LAST:event_DateToggleActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton DateToggle;
    private com.toedter.calendar.JDateChooser endDateChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel7;
    private com.toedter.calendar.JDateChooser startDateChooser;
    // End of variables declaration//GEN-END:variables
}
