/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.jmonitoring.Components;

import de.jmonitoring.utils.swing.EDT;
import java.awt.Point;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import javax.swing.JButton;

/**
 *
 * @author togro
 */
public class MoniSoftProgressBarWidget extends javax.swing.JPanel {

    /**
     * Creates new form MoniSoftProgressBar
     */
    public MoniSoftProgressBarWidget(String name) {
        EDT.always();
        initComponents();
        ProgessBarCancelButton.setToolTipText("Bricht den Vorgang" + " '" + name + "' " + "ab");
        ProgressBar.setToolTipText("Zeigt den Fortschritt von" + " '" + name + "'");
    }

    public void setValue(int v) {
        ProgressBar.setValue(v);
    }

    public void setText(String s) {
        ProgressBar.setString(s);
    }

    public void addProgressCancelButtonActionListener(ActionListener action) {
        ProgessBarCancelButton.addActionListener(action);
    }

    public void removeProgressCancelButtonActionListener(ActionListener action) {
        ProgessBarCancelButton.removeActionListener(action);
    }

    public void setMinMAx(int min, int max) {
        ProgressBar.setMinimum(min);
        ProgressBar.setMaximum(max);
    }

    public void setIndeterminate(boolean indeterminate) {
        ProgressBar.setIndeterminate(indeterminate);
    }

    public void reset() {
        ProgressBar.setString("");
        ProgressBar.setValue(0);
        ProgressBar.setIndeterminate(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProgressBar = new javax.swing.JProgressBar();
        ProgessBarCancelButton = new JButton() {
            public Point getToolTipLocation(MouseEvent event) {
                return new Point(0, -20);
            }
        };

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setLayout(new java.awt.BorderLayout());

        ProgressBar.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        ProgressBar.setMaximumSize(new java.awt.Dimension(32767, 15));
        ProgressBar.setMinimumSize(new java.awt.Dimension(10, 15));
        ProgressBar.setPreferredSize(new java.awt.Dimension(148, 15));
        ProgressBar.setStringPainted(true);
        add(ProgressBar, java.awt.BorderLayout.CENTER);

        ProgessBarCancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/jmonitoring/icons/cross-circle.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/jmonitoring/base/Bundle"); // NOI18N
        ProgessBarCancelButton.setText(bundle.getString("MoniSoft.ProgessBarCancelButton.text")); // NOI18N
        ProgessBarCancelButton.setToolTipText(bundle.getString("MoniSoft.ProgessBarCancelButton.toolTipText")); // NOI18N
        ProgessBarCancelButton.setBorderPainted(false);
        ProgessBarCancelButton.setContentAreaFilled(false);
        ProgessBarCancelButton.setIconTextGap(0);
        ProgessBarCancelButton.setMaximumSize(new java.awt.Dimension(15, 15));
        ProgessBarCancelButton.setMinimumSize(new java.awt.Dimension(15, 15));
        ProgessBarCancelButton.setPreferredSize(new java.awt.Dimension(15, 15));
        ProgessBarCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProgessBarCancelButtonActionPerformed(evt);
            }
        });
        add(ProgessBarCancelButton, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void ProgessBarCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProgessBarCancelButtonActionPerformed
    }//GEN-LAST:event_ProgessBarCancelButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ProgessBarCancelButton;
    private javax.swing.JProgressBar ProgressBar;
    // End of variables declaration//GEN-END:variables
}
