/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.jmonitoring.Components;

import java.awt.Dimension;
import java.util.HashMap;
import javax.swing.Box;
import javax.swing.Box.Filler;

/**
 *
 * @author togro
 */
public class ProgressBarPanel extends javax.swing.JPanel {

    private HashMap<MoniSoftProgressBar, Filler> boxMap = new HashMap<MoniSoftProgressBar, Filler>();
    private Dimension fillerDimenstion = new Dimension(20, 5);
    private Dimension nullDimension = new Dimension(0, 5);

    /**
     * Creates new form ProgressBarPanel
     */
    public ProgressBarPanel() {
        initComponents();
    }

    public MoniSoftProgressBar addProgressBar(String name) {
        MoniSoftProgressBar bar = new MoniSoftProgressBar(name);

        if (!boxMap.isEmpty()) {
            Filler filler = new Box.Filler(fillerDimenstion, fillerDimenstion, fillerDimenstion);
            add(filler);
            boxMap.put(bar, filler);
        } else {
            boxMap.put(bar, new Box.Filler(nullDimension, nullDimension, nullDimension));
        }

        add(bar.asWidget());
        update();
        return bar;
    }

    public void removeProgressBar(MoniSoftProgressBar bar) {
        remove(boxMap.get(bar));
        boxMap.remove(bar);
        remove(bar.asWidget());
        bar = null;
        update();
    }

    public void clear() {
        removeAll();
        update();
    }

    private void update() {
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(32767, 19));
        setMinimumSize(new java.awt.Dimension(300, 19));
        setPreferredSize(new java.awt.Dimension(600, 19));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
